// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	cart "github.com/wansui976/go_zero_shop/apps/app/api/internal/handler/cart"
	home "github.com/wansui976/go_zero_shop/apps/app/api/internal/handler/home"
	order "github.com/wansui976/go_zero_shop/apps/app/api/internal/handler/order"
	product "github.com/wansui976/go_zero_shop/apps/app/api/internal/handler/product"
	productStock "github.com/wansui976/go_zero_shop/apps/app/api/internal/handler/productStock"
	user "github.com/wansui976/go_zero_shop/apps/app/api/internal/handler/user"
	"github.com/wansui976/go_zero_shop/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 添加购物车
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: cart.CartAddHandler(serverCtx),
			},
			{
				// 删除用户购物车
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: cart.CartDeleteHandler(serverCtx),
			},
			{
				// 购物车商品列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: cart.CartListHandler(serverCtx),
			},
			{
				// 更新购物车
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: cart.CartUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/cart"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 首页Banner列表
				Method:  http.MethodGet,
				Path:    "/banner",
				Handler: home.HomeBannerHandler(serverCtx),
			},
			{
				// 限时抢购商品列表
				Method:  http.MethodGet,
				Path:    "/flash-sale",
				Handler: home.FlashSaleHandler(serverCtx),
			},
			{
				// 获取首页信息
				Method:  http.MethodGet,
				Path:    "/index-infos",
				Handler: home.HomeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/home"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建订单
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: order.AddOrderHandler(serverCtx),
			},
			{
				// 获取订单列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: order.OrderListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/order"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 分类商品列表
				Method:  http.MethodGet,
				Path:    "/category/list",
				Handler: product.CategoryListHandler(serverCtx),
			},
			{
				// 商品评论列表
				Method:  http.MethodGet,
				Path:    "/comment",
				Handler: product.ProductCommentHandler(serverCtx),
			},
			{
				// 商品详情
				Method:  http.MethodGet,
				Path:    "/detail/:productId",
				Handler: product.ProductDetailHandler(serverCtx),
			},
			{
				// 商品索引
				Method:  http.MethodPost,
				Path:    "/es",
				Handler: product.ProductEsHandler(serverCtx),
			},
			{
				// 商品搜索
				Method:  http.MethodPost,
				Path:    "/es/search",
				Handler: product.ProductEsSearchHandler(serverCtx),
			},
			{
				// 商品列表（按分类）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: product.ProductListHandler(serverCtx),
			},
			{
				// 推荐商品列表
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: product.RecommendHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/product"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 库存检查与扣减（下单专用）
				Method:  http.MethodPost,
				Path:    "/check-and-update",
				Handler: productStock.CheckAndUpdateStockHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/product/stock"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 添加商品收藏
				Method:  http.MethodPost,
				Path:    "/add-collection",
				Handler: user.UserCollectionAddHandler(serverCtx),
			},
			{
				// 添加收货地址
				Method:  http.MethodPost,
				Path:    "/add-receive-address",
				Handler: user.AddReceiveAddressHandler(serverCtx),
			},
			{
				// 删除商品收藏
				Method:  http.MethodDelete,
				Path:    "/del-collection",
				Handler: user.UserCollectionDelHandler(serverCtx),
			},
			{
				// 删除收货地址
				Method:  http.MethodDelete,
				Path:    "/del-receive-address",
				Handler: user.DelReceiveAddressHandler(serverCtx),
			},
			{
				// 编辑收货地址
				Method:  http.MethodPost,
				Path:    "/edit-receive-address",
				Handler: user.EditReceiveAddressHandler(serverCtx),
			},
			{
				// 获取收藏列表
				Method:  http.MethodGet,
				Path:    "/get-collection-list",
				Handler: user.UserCollectionListHandler(serverCtx),
			},
			{
				// 获取收货地址
				Method:  http.MethodGet,
				Path:    "/get-receive-address",
				Handler: user.UserReceiveAddressHandler(serverCtx),
			},
			{
				// 获取收货地址列表
				Method:  http.MethodGet,
				Path:    "/get-receive-address-list",
				Handler: user.UserReceiveAddressListHandler(serverCtx),
			},
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/user"),
	)
}
