// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: cart.proto

package cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应结构体（符合DTM规范，兼容结果解析）
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"` // 是否成功
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`       // 状态码（200=成功，其他=失败）
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`  // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 添加购物车请求
type CartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`       // 用户ID
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"` // 商品ID
	Price         int64                  `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`         // 加入时商品售价（分）
	Quantity      int64                  `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`   // 商品数量（默认1）
	Selected      int64                  `protobuf:"varint,5,opt,name=Selected,proto3" json:"Selected,omitempty"`   // 是否选中（0=否，1=是，默认1）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemRequest) Reset() {
	*x = CartItemRequest{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRequest) ProtoMessage() {}

func (x *CartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRequest.ProtoReflect.Descriptor instead.
func (*CartItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItemRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItemRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemRequest) GetSelected() int64 {
	if x != nil {
		return x.Selected
	}
	return 0
}

// 购物车列表/清空请求（按用户ID筛选）
type CartListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListRequest) Reset() {
	*x = CartListRequest{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListRequest) ProtoMessage() {}

func (x *CartListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListRequest.ProtoReflect.Descriptor instead.
func (*CartListRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CartListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 更新购物车请求（支持部分字段更新）
type UpdateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`       // 用户ID
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"` // 商品ID
	Quantity      int64                  `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`   // 新数量（可选，不传则不更新）
	Selected      int64                  `protobuf:"varint,4,opt,name=Selected,proto3" json:"Selected,omitempty"`   // 新选中状态（可选，不传则不更新）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartRequest) Reset() {
	*x = UpdateCartRequest{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartRequest) ProtoMessage() {}

func (x *UpdateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateCartRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateCartRequest) GetSelected() int64 {
	if x != nil {
		return x.Selected
	}
	return 0
}

// 删除购物车请求（单商品删除）
type DeleteCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`       // 用户ID
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"` // 商品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartRequest) Reset() {
	*x = DeleteCartRequest{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartRequest) ProtoMessage() {}

func (x *DeleteCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCartRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// 购物车项结构体（对应数据库表字段）
type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                     // 购物车ID
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`             // 用户ID
	ProductId     int64                  `protobuf:"varint,3,opt,name=ProductId,proto3" json:"ProductId,omitempty"`       // 商品ID
	Price         int64                  `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`               // 加入时商品售价（分）
	Quantity      int64                  `protobuf:"varint,5,opt,name=Quantity,proto3" json:"Quantity,omitempty"`         // 商品数量
	Selected      int64                  `protobuf:"varint,6,opt,name=Selected,proto3" json:"Selected,omitempty"`         // 是否选中（0=否，1=是）
	DeleteStatus  int64                  `protobuf:"varint,7,opt,name=DeleteStatus,proto3" json:"DeleteStatus,omitempty"` // 删除状态（0=正常，1=删除）
	CreateTime    string                 `protobuf:"bytes,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`      // 创建时间（格式：yyyy-MM-dd HH:mm:ss）
	UpdateTime    string                 `protobuf:"bytes,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`      // 更新时间（格式：yyyy-MM-dd HH:mm:ss）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{5}
}

func (x *CartItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetSelected() int64 {
	if x != nil {
		return x.Selected
	}
	return 0
}

func (x *CartItem) GetDeleteStatus() int64 {
	if x != nil {
		return x.DeleteStatus
	}
	return 0
}

func (x *CartItem) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *CartItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 购物车列表响应
type CartListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`       // 是否成功
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`             // 状态码
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`        // 提示信息
	CartItems     []*CartItem            `protobuf:"bytes,4,rep,name=CartItems,proto3" json:"CartItems,omitempty"`    // 购物车项列表
	TotalCount    int64                  `protobuf:"varint,5,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"` // 商品总数
	TotalPrice    int64                  `protobuf:"varint,6,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"` // 商品总价（分，仅计算选中商品）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListResponse) Reset() {
	*x = CartListResponse{}
	mi := &file_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListResponse) ProtoMessage() {}

func (x *CartListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListResponse.ProtoReflect.Descriptor instead.
func (*CartListResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CartListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CartListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CartListResponse) GetCartItems() []*CartItem {
	if x != nil {
		return x.CartItems
	}
	return nil
}

func (x *CartListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CartListResponse) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x12\x04cart\"R\n" +
	"\bResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"\x95\x01\n" +
	"\x0fCartItemRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x03R\x05Price\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\x03R\bQuantity\x12\x1a\n" +
	"\bSelected\x18\x05 \x01(\x03R\bSelected\")\n" +
	"\x0fCartListRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\"\x81\x01\n" +
	"\x11UpdateCartRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\x12\x1a\n" +
	"\bQuantity\x18\x03 \x01(\x03R\bQuantity\x12\x1a\n" +
	"\bSelected\x18\x04 \x01(\x03R\bSelected\"I\n" +
	"\x11DeleteCartRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\"\x82\x02\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1c\n" +
	"\tProductId\x18\x03 \x01(\x03R\tProductId\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x03R\x05Price\x12\x1a\n" +
	"\bQuantity\x18\x05 \x01(\x03R\bQuantity\x12\x1a\n" +
	"\bSelected\x18\x06 \x01(\x03R\bSelected\x12\"\n" +
	"\fDeleteStatus\x18\a \x01(\x03R\fDeleteStatus\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\b \x01(\tR\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\t \x01(\tR\n" +
	"UpdateTime\"\xc8\x01\n" +
	"\x10CartListResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12,\n" +
	"\tCartItems\x18\x04 \x03(\v2\x0e.cart.CartItemR\tCartItems\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x05 \x01(\x03R\n" +
	"TotalCount\x12\x1e\n" +
	"\n" +
	"TotalPrice\x18\x06 \x01(\x03R\n" +
	"TotalPrice2\xcc\x02\n" +
	"\x04Cart\x120\n" +
	"\aAddCart\x12\x15.cart.CartItemRequest\x1a\x0e.cart.Response\x12<\n" +
	"\vGetCartList\x12\x15.cart.CartListRequest\x1a\x16.cart.CartListResponse\x125\n" +
	"\n" +
	"UpdateCart\x12\x17.cart.UpdateCartRequest\x1a\x0e.cart.Response\x125\n" +
	"\n" +
	"DeleteCart\x12\x17.cart.DeleteCartRequest\x1a\x0e.cart.Response\x122\n" +
	"\tClearCart\x12\x15.cart.CartListRequest\x1a\x0e.cart.Response\x122\n" +
	"\tCheckCart\x12\x15.cart.CartItemRequest\x1a\x0e.cart.ResponseB\bZ\x06./cartb\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cart_proto_goTypes = []any{
	(*Response)(nil),          // 0: cart.Response
	(*CartItemRequest)(nil),   // 1: cart.CartItemRequest
	(*CartListRequest)(nil),   // 2: cart.CartListRequest
	(*UpdateCartRequest)(nil), // 3: cart.UpdateCartRequest
	(*DeleteCartRequest)(nil), // 4: cart.DeleteCartRequest
	(*CartItem)(nil),          // 5: cart.CartItem
	(*CartListResponse)(nil),  // 6: cart.CartListResponse
}
var file_cart_proto_depIdxs = []int32{
	5, // 0: cart.CartListResponse.CartItems:type_name -> cart.CartItem
	1, // 1: cart.Cart.AddCart:input_type -> cart.CartItemRequest
	2, // 2: cart.Cart.GetCartList:input_type -> cart.CartListRequest
	3, // 3: cart.Cart.UpdateCart:input_type -> cart.UpdateCartRequest
	4, // 4: cart.Cart.DeleteCart:input_type -> cart.DeleteCartRequest
	2, // 5: cart.Cart.ClearCart:input_type -> cart.CartListRequest
	1, // 6: cart.Cart.CheckCart:input_type -> cart.CartItemRequest
	0, // 7: cart.Cart.AddCart:output_type -> cart.Response
	6, // 8: cart.Cart.GetCartList:output_type -> cart.CartListResponse
	0, // 9: cart.Cart.UpdateCart:output_type -> cart.Response
	0, // 10: cart.Cart.DeleteCart:output_type -> cart.Response
	0, // 11: cart.Cart.ClearCart:output_type -> cart.Response
	0, // 12: cart.Cart.CheckCart:output_type -> cart.Response
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
