// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type Banner struct {
	ID   int64  `json:"id"`   // Banner ID
	Name string `json:"name"` // Banner 名称
	URL  string `json:"url"`  // 图片地址（CDN 全路径）
}

type CartAddRequest struct {
	PID      int64 `json:"pid"`
	Quantity int64 `json:"quantity"`
	Price    int64 `json:"price"`
}

type CartDeleteRequest struct {
	PID int64 `json:"pid,required"`
}

type CartListRequest struct {
}

type CartListResponse struct {
	Products []*CartProduct `json:"products"` // 购物车商品列表
}

type CartProduct struct {
	Product *Product `json:"product"` // 商品基础信息
	Count   int64    `json:"count"`   // 购买数量（>=1）
}

type CartUpdateRequest struct {
	PID      int64 `json:"pid,required"`
	Quantity int64 `json:"quantity,required"`
}

type CategoryListRequest struct {
	Cursor   int64  `form:"cursor"`                 // 分页游标（首次请求传0）
	Ps       int64  `form:"ps,default=20"`          // 每页条数（默认20，最大50）
	Category string `form:"category"`               // 分类名称（为空时查全部分类）
	Sort     string `form:"sort,default=recommend"` // 排序规则：recommend-推荐，price_asc-价低到高，price_desc-价高到低，newest-最新
}

type CategoryListResponse struct {
	Products   []*Product `json:"products"`    // 分类商品列表
	IsEnd      bool       `json:"is_end"`      // 是否最后一页
	LastCursor int64      `json:"last_cursor"` // 下一页游标
}

type CheckAndUpdateStockRequest struct {
	ProductID int64  `json:"product_id,required"` // 商品 ID（必填）
	RequestID string `json:"request_id,required"` // 请求唯一 ID（幂等校验用）
	Quantity  int64  `json:"quantity,required"`   // 扣减数量（>=1）
}

type CheckAndUpdateStockResponse struct {
	Success     bool  `json:"success"`      // 是否扣减成功
	RemainStock int64 `json:"remain_stock"` // 扣减后剩余库存
}

type Comment struct {
	ID         int64     `json:"id"`          // 评论 ID
	ProductID  int64     `json:"product_id"`  // 关联商品 ID
	Content    string    `json:"content"`     // 评论内容
	Images     []*Image  `json:"images"`      // 评论附图（最多9张）
	User       *UserMini `json:"user"`        // 评论用户信息（脱敏）
	CreateTime int64     `json:"create_time"` // 评论时间（时间戳，毫秒级）
	UpdateTime int64     `json:"update_time"` // 更新时间（时间戳，毫秒级）
}

type CommonResponse struct {
	ResultCode int64       `json:"resultCode"` // 前端核心判断字段：200=成功，非200=失败
	Msg        string      `json:"msg"`        // 错误提示信息（成功时为"success"）
	Data       interface{} `json:"data"`       // 业务数据（成功时返回，失败时可为空）
}

type FlashSaleResponse struct {
	StartTime int64      `json:"start_time"` // 抢购开始时间（时间戳，毫秒级）
	EndTime   int64      `json:"end_time"`   // 抢购结束时间（时间戳，毫秒级）
	Products  []*Product `json:"products"`   // 限时抢购商品列表
}

type HomeBannerResponse struct {
	Banners []*Banner `json:"banners"` // Banner 列表（最多5条）
}

type HomeResponse struct {
	CarouselList []*ProductItem `json:"carousel_list"`
	NewGoodses   []*ProductItem `json:"new_goodses"`
	HotGoodses   []*ProductItem `json:"hot_goodses"`
}

type Image struct {
	ID  int64  `json:"id"`  // 图片 ID
	URL string `json:"url"` // 图片地址（CDN 全路径）
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type Order struct {
	OrderID         string              `json:"order_id"` // 订单唯一 ID（雪花算法生成）
	Status          int32               `json:"status"`   // 订单状态：1-待支付，2-已支付，3-已发货，4-已完成，5-已取消
	Payment         int64               `json:"payment"`  // 实付金额（单位：分）
	Payment_type    int32               `json:"payment_type"`
	TotalPrice      int64               `json:"total_price"` // 订单总价（单位：分）
	CreateTime      int64               `json:"create_time"` // 下单时间（时间戳，毫秒级）
	ProductItems    []*OrderProductItem `json:"productitems"`
	ReceiverName    string              `json:"receiver_name"`
	ReceiverPhone   string              `json:"receiver_phone"`
	ReceiverAddress string              `json:"receiver_address"`
}

type OrderAddReq struct {
	RequestId        string       `json:"request_id,omitempty"` // 可选：前端传入幂等请求ID
	ReceiveAddressId string       `json:"receiveAddressId"`     //用户收货地址表id
	Items            []*OrderItem `json:"items"`
	PaymentType      int8         `json:"payment_type"` //支付类型,1-微信支付 2-支付宝支付
}

type OrderAddResp struct {
	Id string `json:"id"` //订单id
}

type OrderItem struct {
	Id    int64 `json:"id"`    //商品id
	Count int64 `json:"count"` //数量
}

type OrderListRequest struct {
}

type OrderListResponse struct {
	OrderInfo Order `json:"orderInfo"`
}

type OrderProductItem struct {
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

type Product struct {
	Id                  int64   `json:"id"`                    // 商品ID (SPU)
	Name                string  `json:"name"`                  // 商品名称
	Brief               string  `json:"brief"`                 // 商品简介
	Keywords            string  `json:"keywords"`              // 关键词，用于搜索
	ImageUrl            string  `json:"image_url"`             // 主图URL
	CategoryId          int64   `json:"category_id"`           // 主分类ID
	CategoryName        string  `json:"category_name"`         // 主分类名称
	CategoryIds         string  `json:"category_ids"`          // 所有分类ID集合（逗号分隔）
	BrandId             int64   `json:"brand_id"`              // 品牌ID
	BrandName           string  `json:"brand_name"`            // 品牌名称
	Price               int64   `json:"price"`                 // 售价
	Stock               int64   `json:"stock"`                 // 当前库存
	LowStock            int64   `json:"low_stock"`             // 库存预警值
	Sales               int64   `json:"sales"`                 // 销量
	Unit                string  `json:"unit"`                  // 单位（件 / 台 / 箱）
	Weight              float64 `json:"weight"`                // 重量(kg)
	DetailTitle         string  `json:"detail_title"`          // 详情标题
	DetailDesc          string  `json:"detail_desc"`           // 详情描述
	DetailHtml          string  `json:"detail_html"`           // 富文本详情内容（HTML）
	Sort                int64   `json:"sort"`                  // 排序值
	NewStatusSort       int64   `json:"new_status_sort"`       // 新品排序
	RecommendStatusSort int64   `json:"recommend_status_sort"` // 推荐排序
	Status              int64   `json:"status"`                // 商品状态：0-下架，1-上架
	CreateTime          int64   `json:"create_time"`           // 创建时间
	UpdateTime          int64   `json:"update_time"`           // 更新时间
}

type ProductCommentRequest struct {
	ProductID int64 `form:"product_id,required"` // 商品 ID（必填）
	Cursor    int64 `form:"cursor"`              // 分页游标（首次传0）
	Ps        int64 `form:"ps,default=20"`       // 每页条数（默认20，最大50）
}

type ProductCommentResponse struct {
	Comments   []*Comment `json:"comments"`    // 商品评论列表
	IsEnd      bool       `json:"is_end"`      // 是否最后一页
	LastCursor int64      `json:"last_cursor"` // 下一页游标
	TotalCount int64      `json:"total_count"` // 评论总数
}

type ProductDetailRequest struct {
	ProductID int64 `path:"productId"` // 商品 ID（必填）
}

type ProductDetailResponse struct {
	Product      *Product   `json:"product"`       // 商品详情
	Comments     []*Comment `json:"comments"`      // 热门评论（前3条）
	CommentTotal int64      `json:"comment_total"` // 评论总数
}

type ProductEsRequest struct {
}

type ProductEsSearchRequest struct {
	Keyword   string `json:"keyword"`
	Page_num  int64  `json:"page_num"`
	Page_size int64  `json:"page_size"`
	Sort      int32  `json:"sort"` ////排序字段:0->按相关度；1->按新品；2->按销量；3->价格从低到高；4->价格从高到低
}

type ProductItem struct {
	GoodsId       int64  `json:"goods_id"`
	GoodsName     string `json:"goods_name"`      //商品名称
	SellingPrice  int64  `json:"selling_price"`   //售价
	GoodsCoverImg string `json:"goods_cover_img"` //商品封面图片URL
}

type ProductListRequest struct {
	Cursor     int64 `form:"cursor,default=0"` // 分页游标（默认0）
	CategoryID int32 `form:"category_id"`      // 分类 ID（不传查全部分类）
	Ps         int32 `form:"ps,default=10"`    // 每页条数（默认10，最大50）
}

type ProductListResponse struct {
	Products   []*Product `json:"products"`    // 商品列表
	IsEnd      bool       `json:"is_end"`      // 是否最后一页
	LastCursor int64      `json:"last_cursor"` // 下一页游标
}

type RecommendRequest struct {
	Cursor int64 `form:"cursor"`        // 分页游标（首次请求传0）
	Ps     int64 `form:"ps,default=20"` // 每页条数（默认20，最大50）
}

type RecommendResponse struct {
	Products   []*Product `json:"products"`    // 推荐商品列表
	IsEnd      bool       `json:"is_end"`      // 是否最后一页（true=无更多）
	LastCursor int64      `json:"last_cursor"` // 下一页游标（IsEnd=true 时为0）
}

type UserCollectionAddReq struct {
	ProductId int64 `json:"product_id"` // 商品id
}

type UserCollectionAddRes struct {
}

type UserCollectionDelReq struct {
	Id int64 `json:"id"` // 收藏Id
}

type UserCollectionDelRes struct {
}

type UserCollectionListReq struct {
}

type UserCollectionListRes struct {
	ProductId []int64 `json:"product_id"` // 商品id
}

type UserInfo struct {
	Id            uint64 `json:"id" db:"id"`                         // 对应数据库 id
	Username      string `json:"username" db:"username"`             // 对应数据库 username
	Phone         string `json:"phone" db:"phone"`                   // 对应数据库 phone
	IntroduceSign string `json:"introduce_sign" db:"introduce_sign"` // 关键：JSON标签为 introduce_sign
	CreateTime    int64  `json:"create_time" db:"create_time"`       // 数据库时间转时间戳
	UpdateTime    int64  `json:"update_time" db:"update_time"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo UserInfo `json:"userInfo"`
}

type UserMini struct {
	ID     int64  `json:"id"`     // 用户 ID
	Name   string `json:"name"`   // 用户名（脱敏，如"张*三"）
	Avatar string `json:"avatar"` // 用户头像地址
}

type UserReceiveAddress struct {
	Id            int64  `json:"id"`
	Uid           uint64 `json:"uid"`            //用户id
	Name          string `json:"name"`           //收货人名称
	Phone         string `json:"phone"`          //手机号
	IsDefault     int32  `json:"is_default"`     //是否为默认地址
	Province      string `json:"province"`       //省份/直辖市
	City          string `json:"city"`           //城市
	Region        string `json:"region"`         //区
	DetailAddress string `json:"detail_address"` //详细地址(街道)
	IsDelete      int32  `json:"is_delete"`      //是否删除
	CreateTime    int64  `json:"create_time"`    //数据创建时间[禁止在代码中赋值]
	UpdateTime    int64  `json:"update_time"`    //数据更新时间[禁止在代码中赋值]
}

type UserReceiveAddressAddReq struct {
	Name          string `json:"name"`           //收货人名称
	Phone         string `json:"phone"`          //手机号
	IsDefault     int32  `json:"is_default"`     //是否为默认地址
	Province      string `json:"province"`       //省份/直辖市
	City          string `json:"city"`           //城市
	Region        string `json:"region"`         //区
	DetailAddress string `json:"detail_address"` //详细地址(街道)
}

type UserReceiveAddressAddRes struct {
}

type UserReceiveAddressDelReq struct {
	Id int64 `json:"id"`
}

type UserReceiveAddressDelRes struct {
}

type UserReceiveAddressEditReq struct {
	Id            string `json:"id"`
	Name          string `json:"name"`           //收货人名称
	Phone         string `json:"phone"`          //手机号
	IsDefault     int32  `json:"is_default"`     //是否为默认地址
	Province      string `json:"province"`       //省份/直辖市
	City          string `json:"city"`           //城市
	Region        string `json:"region"`         //区
	DetailAddress string `json:"detail_address"` //详细地址(街道)
}

type UserReceiveAddressEditRes struct {
}

type UserReceiveAddressListReq struct {
}

type UserReceiveAddressListRes struct {
	List []UserReceiveAddress `json:"list"`
}

type UserReceiveAddressReq struct {
	Id int64 `form:"id"`
}

type UserReceiveAddressRes struct {
	Address UserReceiveAddress `json:"address"`
}
