apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-rpc-config
  namespace: go-zero-shop
data:
  cart.yaml: |
    Name: cart.rpc
    ListenOn: 0.0.0.0:8084

    Etcd:
      Hosts:
      - etcd:2379
      Key: cart.rpc

    DataSource: root:123456@tcp(mysql:3306)/cart?charset=utf8mb4&parseTime=true&loc=Local

    CacheRedis:
      - Host: redis:6379
        Pass: ""
        Type: node

    Prometheus:
      Host: 0.0.0.0
      Port: 9101
      Path: /metrics

    Telemetry:
      Name: cart-rpc
      Endpoint: http://jaeger:14268/api/traces
      Sampler: 1.0
      Batcher: jaeger
