apiVersion: v1
kind: ConfigMap
metadata:
  name: dtm-config
  namespace: go-zero-shop
data:
  conf.yml: |
    Store:
      Driver: mysql
      Host: mysql
      Port: 3306
      User: root
      Password: "123456"
      Db: dtm
    MicroService:
      Driver: dtm-driver-gozero
      Target: etcd://etcd:2379/dtmservice
      EndPoint: dtm:36790
    HttpPort: 36789
    GrpcPort: 36790
    LogLevel: info
