apiVersion: v1
kind: ConfigMap
metadata:
  name: seckill-rpc-config
  namespace: go-zero-shop
data:
  seckill.yaml: |
    Name: seckill.rpc
    ListenOn: 0.0.0.0:9889
    Mode: dev
    Etcd:
      Hosts:
      - etcd:2379
      Key: seckill.rpc
    BizRedis:
      Host: redis:6379
      Pass: ""
      Type: node
    ProductRPC:
      Etcd:
        Hosts:
          - etcd:2379
        Key: product.rpc
    Kafka:
      Addrs:
        - kafka:9092
      SeckillTopic: seckill-topic

    Telemetry:
      Name: seckill-rpc
      Endpoint: http://jaeger:14268/api/traces
      Sampler: 1.0
      Batcher: jaeger

    Prometheus:
      Host: 0.0.0.0
      Port: 9101
      Path: /metrics
