// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: order.proto

package server

import (
	"context"

	"github.com/wansui976/go_zero_shop/apps/order/rpc/internal/logic"
	"github.com/wansui976/go_zero_shop/apps/order/rpc/internal/svc"
	"github.com/wansui976/go_zero_shop/apps/order/rpc/order"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 查询订单列表
func (s *OrderServiceServer) Orders(ctx context.Context, in *order.OrdersRequest) (*order.OrdersResponse, error) {
	l := logic.NewOrdersLogic(ctx, s.svcCtx)
	return l.Orders(in)
}

// 查询订单详情
func (s *OrderServiceServer) GetOrderById(ctx context.Context, in *order.GetOrderByIdRequest) (*order.GetOrderByIdResponse, error) {
	l := logic.NewGetOrderByIdLogic(ctx, s.svcCtx)
	return l.GetOrderById(in)
}

// 普通下单（可选择是否走 DTM）
func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 订单回滚（普通下单失败兜底）
func (s *OrderServiceServer) RollbackOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewRollbackOrderLogic(ctx, s.svcCtx)
	return l.RollbackOrder(in)
}

// 正式取消订单（用于超时未支付等场景）
func (s *OrderServiceServer) CancelOrder(ctx context.Context, in *order.CancelOrderRequest) (*order.CancelOrderResponse, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

// Try：创建半成品订单
func (s *OrderServiceServer) CreateOrderDTM(ctx context.Context, in *order.AddOrderRequest) (*order.AddOrderResponse, error) {
	l := logic.NewCreateOrderDTMLogic(ctx, s.svcCtx)
	return l.CreateOrderDTM(in)
}

// Confirm：确认订单（扣库存 + 改状态）
func (s *OrderServiceServer) CreateOrderDTMConfirm(ctx context.Context, in *order.CreateOrderDTMConfirmRequest) (*order.CreateOrderDTMConfirmResponse, error) {
	l := logic.NewCreateOrderDTMConfirmLogic(ctx, s.svcCtx)
	return l.CreateOrderDTMConfirm(in)
}

// Cancel：回滚订单
func (s *OrderServiceServer) CreateOrderDTMRevert(ctx context.Context, in *order.AddOrderRequest) (*order.AddOrderResponse, error) {
	l := logic.NewCreateOrderDTMRevertLogic(ctx, s.svcCtx)
	return l.CreateOrderDTMRevert(in)
}
