// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: pay.proto

package payservice

import (
	"context"

	"github.com/wansui976/go_zero_shop/apps/pay/rpc/pay"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePaymentRequest        = pay.CreatePaymentRequest
	CreatePaymentResponse       = pay.CreatePaymentResponse
	GetPaymentByOrderIdRequest  = pay.GetPaymentByOrderIdRequest
	GetPaymentByOrderIdResponse = pay.GetPaymentByOrderIdResponse
	GetRefundByIdRequest        = pay.GetRefundByIdRequest
	GetRefundByIdResponse       = pay.GetRefundByIdResponse
	PaymentCallbackRequest      = pay.PaymentCallbackRequest
	PaymentCallbackResponse     = pay.PaymentCallbackResponse
	PaymentInfo                 = pay.PaymentInfo
	RefundInfo                  = pay.RefundInfo
	RefundRequest               = pay.RefundRequest
	RefundResponse              = pay.RefundResponse

	PayService interface {
		// 创建支付订单
		CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
		// 查询支付状态
		GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, opts ...grpc.CallOption) (*GetPaymentByOrderIdResponse, error)
		// 支付回调（第三方支付回调）
		PaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error)
		// 发起退款
		Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
		// 查询退款状态
		GetRefundById(ctx context.Context, in *GetRefundByIdRequest, opts ...grpc.CallOption) (*GetRefundByIdResponse, error)
	}

	defaultPayService struct {
		cli zrpc.Client
	}
)

func NewPayService(cli zrpc.Client) PayService {
	return &defaultPayService{
		cli: cli,
	}
}

// 创建支付订单
func (m *defaultPayService) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	client := pay.NewPayServiceClient(m.cli.Conn())
	return client.CreatePayment(ctx, in, opts...)
}

// 查询支付状态
func (m *defaultPayService) GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, opts ...grpc.CallOption) (*GetPaymentByOrderIdResponse, error) {
	client := pay.NewPayServiceClient(m.cli.Conn())
	return client.GetPaymentByOrderId(ctx, in, opts...)
}

// 支付回调（第三方支付回调）
func (m *defaultPayService) PaymentCallback(ctx context.Context, in *PaymentCallbackRequest, opts ...grpc.CallOption) (*PaymentCallbackResponse, error) {
	client := pay.NewPayServiceClient(m.cli.Conn())
	return client.PaymentCallback(ctx, in, opts...)
}

// 发起退款
func (m *defaultPayService) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	client := pay.NewPayServiceClient(m.cli.Conn())
	return client.Refund(ctx, in, opts...)
}

// 查询退款状态
func (m *defaultPayService) GetRefundById(ctx context.Context, in *GetRefundByIdRequest, opts ...grpc.CallOption) (*GetRefundByIdResponse, error) {
	client := pay.NewPayServiceClient(m.cli.Conn())
	return client.GetRefundById(ctx, in, opts...)
}
