// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productOperationFieldNames          = builder.RawFieldNames(&ProductOperation{})
	productOperationRows                = strings.Join(productOperationFieldNames, ",")
	productOperationRowsExpectAutoSet   = strings.Join(stringx.Remove(productOperationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productOperationRowsWithPlaceHolder = strings.Join(stringx.Remove(productOperationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProductOperationIdPrefix = "cache:productOperation:id:"
)

type (
	productOperationModel interface {
		Insert(ctx context.Context, data *ProductOperation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProductOperation, error)
		Update(ctx context.Context, data *ProductOperation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductOperationModel struct {
		sqlc.CachedConn
		table string
	}

	ProductOperation struct {
		Id            int64          `db:"id"`             // 操作记录ID
		ProductId     int64          `db:"product_id"`     // 商品ID
		OperatorId    sql.NullInt64  `db:"operator_id"`    // 操作人ID
		OperatorName  sql.NullString `db:"operator_name"`  // 操作人名称
		OperationType string         `db:"operation_type"` // 操作类型（create/update/online/offline/adjust_stock等）
		BeforeData    sql.NullString `db:"before_data"`    // 操作前数据（JSON快照）
		AfterData     sql.NullString `db:"after_data"`     // 操作后数据（JSON快照）
		Remark        sql.NullString `db:"remark"`         // 备注
		CreateTime    time.Time      `db:"create_time"`    // 操作时间
	}
)

func newProductOperationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductOperationModel {
	return &defaultProductOperationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`product_operation`",
	}
}

func (m *defaultProductOperationModel) Delete(ctx context.Context, id int64) error {
	productOperationIdKey := fmt.Sprintf("%s%v", cacheProductOperationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, productOperationIdKey)
	return err
}

func (m *defaultProductOperationModel) FindOne(ctx context.Context, id int64) (*ProductOperation, error) {
	productOperationIdKey := fmt.Sprintf("%s%v", cacheProductOperationIdPrefix, id)
	var resp ProductOperation
	err := m.QueryRowCtx(ctx, &resp, productOperationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productOperationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductOperationModel) Insert(ctx context.Context, data *ProductOperation) (sql.Result, error) {
	productOperationIdKey := fmt.Sprintf("%s%v", cacheProductOperationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, productOperationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProductId, data.OperatorId, data.OperatorName, data.OperationType, data.BeforeData, data.AfterData, data.Remark)
	}, productOperationIdKey)
	return ret, err
}

func (m *defaultProductOperationModel) Update(ctx context.Context, data *ProductOperation) error {
	productOperationIdKey := fmt.Sprintf("%s%v", cacheProductOperationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productOperationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProductId, data.OperatorId, data.OperatorName, data.OperationType, data.BeforeData, data.AfterData, data.Remark, data.Id)
	}, productOperationIdKey)
	return err
}

func (m *defaultProductOperationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductOperationIdPrefix, primary)
}

func (m *defaultProductOperationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productOperationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductOperationModel) tableName() string {
	return m.table
}
