// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productFieldNames          = builder.RawFieldNames(&Product{})
	productRows                = strings.Join(productFieldNames, ",")
	productRowsExpectAutoSet   = strings.Join(stringx.Remove(productFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productRowsWithPlaceHolder = strings.Join(stringx.Remove(productFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProductIdPrefix = "cache:product:id:"
)

type (
	productModel interface {
		Insert(ctx context.Context, data *Product) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Product, error)
		Update(ctx context.Context, data *Product) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductModel struct {
		sqlc.CachedConn
		table string
	}

	Product struct {
		Id                  int64          `db:"id"`                    // 商品ID (SPU)
		Name                string         `db:"name"`                  // 商品名称
		Brief               sql.NullString `db:"brief"`                 // 商品简介
		Keywords            sql.NullString `db:"keywords"`              // 关键词，用于搜索
		ImageUrl            sql.NullString `db:"image_url"`             // 主图URL
		CategoryId          sql.NullInt64  `db:"category_id"`           // 主分类ID
		CategoryName        sql.NullString `db:"category_name"`         // 主分类名称
		CategoryIds         sql.NullString `db:"category_ids"`          // 所有分类ID集合（逗号分隔）
		BrandId             sql.NullInt64  `db:"brand_id"`              // 品牌ID
		BrandName           sql.NullString `db:"brand_name"`            // 品牌名称
		Price               int64          `db:"price"`                 // 售价
		Stock               int64          `db:"stock"`                 // 当前库存
		LowStock            int64          `db:"low_stock"`             // 库存预警值
		Sales               int64          `db:"sales"`                 // 销量
		Unit                sql.NullString `db:"unit"`                  // 单位（件 / 台 / 箱）
		Weight              float64        `db:"weight"`                // 重量(kg)
		DetailTitle         sql.NullString `db:"detail_title"`          // 详情标题
		DetailDesc          sql.NullString `db:"detail_desc"`           // 详情描述
		DetailHtml          sql.NullString `db:"detail_html"`           // 富文本详情内容（HTML）
		Sort                int64          `db:"sort"`                  // 排序值
		NewStatusSort       int64          `db:"new_status_sort"`       // 新品排序
		RecommendStatusSort int64          `db:"recommend_status_sort"` // 推荐排序
		Status              int64          `db:"status"`                // 商品状态：0-下架，1-上架
		CreateTime          time.Time      `db:"create_time"`           // 创建时间
		UpdateTime          time.Time      `db:"update_time"`           // 更新时间
	}
)

func newProductModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductModel {
	return &defaultProductModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`product`",
	}
}

func (m *defaultProductModel) Delete(ctx context.Context, id int64) error {
	productIdKey := fmt.Sprintf("%s%v", cacheProductIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, productIdKey)
	return err
}

func (m *defaultProductModel) FindOne(ctx context.Context, id int64) (*Product, error) {
	productIdKey := fmt.Sprintf("%s%v", cacheProductIdPrefix, id)
	var resp Product
	err := m.QueryRowCtx(ctx, &resp, productIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductModel) Insert(ctx context.Context, data *Product) (sql.Result, error) {
	productIdKey := fmt.Sprintf("%s%v", cacheProductIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, productRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Brief, data.Keywords, data.ImageUrl, data.CategoryId, data.CategoryName, data.CategoryIds, data.BrandId, data.BrandName, data.Price, data.Stock, data.LowStock, data.Sales, data.Unit, data.Weight, data.DetailTitle, data.DetailDesc, data.DetailHtml, data.Sort, data.NewStatusSort, data.RecommendStatusSort, data.Status)
	}, productIdKey)
	return ret, err
}

func (m *defaultProductModel) Update(ctx context.Context, data *Product) error {
	productIdKey := fmt.Sprintf("%s%v", cacheProductIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Brief, data.Keywords, data.ImageUrl, data.CategoryId, data.CategoryName, data.CategoryIds, data.BrandId, data.BrandName, data.Price, data.Stock, data.LowStock, data.Sales, data.Unit, data.Weight, data.DetailTitle, data.DetailDesc, data.DetailHtml, data.Sort, data.NewStatusSort, data.RecommendStatusSort, data.Status, data.Id)
	}, productIdKey)
	return err
}

func (m *defaultProductModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductIdPrefix, primary)
}

func (m *defaultProductModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductModel) tableName() string {
	return m.table
}
