// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: pay.proto

package server

import (
	"context"

	"github.com/wansui976/go_zero_shop/internal/logic"
	"github.com/wansui976/go_zero_shop/internal/svc"
	"github.com/wansui976/go_zero_shop/pay"
)

type PayServiceServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedPayServiceServer
}

func NewPayServiceServer(svcCtx *svc.ServiceContext) *PayServiceServer {
	return &PayServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建支付订单
func (s *PayServiceServer) CreatePayment(ctx context.Context, in *pay.CreatePaymentRequest) (*pay.CreatePaymentResponse, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}

// 查询支付状态
func (s *PayServiceServer) GetPaymentByOrderId(ctx context.Context, in *pay.GetPaymentByOrderIdRequest) (*pay.GetPaymentByOrderIdResponse, error) {
	l := logic.NewGetPaymentByOrderIdLogic(ctx, s.svcCtx)
	return l.GetPaymentByOrderId(in)
}

// 支付回调（第三方支付回调）
func (s *PayServiceServer) PaymentCallback(ctx context.Context, in *pay.PaymentCallbackRequest) (*pay.PaymentCallbackResponse, error) {
	l := logic.NewPaymentCallbackLogic(ctx, s.svcCtx)
	return l.PaymentCallback(in)
}

// 发起退款
func (s *PayServiceServer) Refund(ctx context.Context, in *pay.RefundRequest) (*pay.RefundResponse, error) {
	l := logic.NewRefundLogic(ctx, s.svcCtx)
	return l.Refund(in)
}

// 查询退款状态
func (s *PayServiceServer) GetRefundById(ctx context.Context, in *pay.GetRefundByIdRequest) (*pay.GetRefundByIdResponse, error) {
	l := logic.NewGetRefundByIdLogic(ctx, s.svcCtx)
	return l.GetRefundById(in)
}
