// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package userclient

import (
	"context"

	"github.com/wansui976/go_zero_shop/apps/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest                   = user.LoginRequest
	LoginResponse                  = user.LoginResponse
	UserCollectionAddRequest       = user.UserCollectionAddRequest
	UserCollectionAddResponse      = user.UserCollectionAddResponse
	UserCollectionDelRequest       = user.UserCollectionDelRequest
	UserCollectionDelResponse      = user.UserCollectionDelResponse
	UserCollectionListRequest      = user.UserCollectionListRequest
	UserCollectionListResponse     = user.UserCollectionListResponse
	UserInfo                       = user.UserInfo
	UserInfoRequest                = user.UserInfoRequest
	UserInfoResponse               = user.UserInfoResponse
	UserReceiveAddress             = user.UserReceiveAddress
	UserReceiveAddressAddRequest   = user.UserReceiveAddressAddRequest
	UserReceiveAddressAddResponse  = user.UserReceiveAddressAddResponse
	UserReceiveAddressDelRequest   = user.UserReceiveAddressDelRequest
	UserReceiveAddressDelResponse  = user.UserReceiveAddressDelResponse
	UserReceiveAddressEditRequest  = user.UserReceiveAddressEditRequest
	UserReceiveAddressEditResponse = user.UserReceiveAddressEditResponse
	UserReceiveAddressInfoRequest  = user.UserReceiveAddressInfoRequest
	UserReceiveAddressListRequest  = user.UserReceiveAddressListRequest
	UserReceiveAddressListResponse = user.UserReceiveAddressListResponse

	User interface {
		// 登录
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 获取用户信息
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		// 添加收获地址
		AddUserReceiveAddress(ctx context.Context, in *UserReceiveAddressAddRequest, opts ...grpc.CallOption) (*UserReceiveAddressAddResponse, error)
		// 编辑收获地址
		EditUserReceiveAddress(ctx context.Context, in *UserReceiveAddressEditRequest, opts ...grpc.CallOption) (*UserReceiveAddressEditResponse, error)
		// 删除收获地址
		DelUserReceiveAddress(ctx context.Context, in *UserReceiveAddressDelRequest, opts ...grpc.CallOption) (*UserReceiveAddressDelResponse, error)
		// 获取收获地址列表
		GetUserReceiveAddressList(ctx context.Context, in *UserReceiveAddressListRequest, opts ...grpc.CallOption) (*UserReceiveAddressListResponse, error)
		// 添加收藏
		AddUserCollection(ctx context.Context, in *UserCollectionAddRequest, opts ...grpc.CallOption) (*UserCollectionAddResponse, error)
		// 删除收藏
		DelUserCollection(ctx context.Context, in *UserCollectionDelRequest, opts ...grpc.CallOption) (*UserCollectionDelResponse, error)
		// 收藏列表
		GetUserCollectionList(ctx context.Context, in *UserCollectionListRequest, opts ...grpc.CallOption) (*UserCollectionListResponse, error)
		// 根据主键id,查询收获地址
		GetUserReceiveAddressInfo(ctx context.Context, in *UserReceiveAddressInfoRequest, opts ...grpc.CallOption) (*UserReceiveAddress, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 登录
func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

// 添加收获地址
func (m *defaultUser) AddUserReceiveAddress(ctx context.Context, in *UserReceiveAddressAddRequest, opts ...grpc.CallOption) (*UserReceiveAddressAddResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddUserReceiveAddress(ctx, in, opts...)
}

// 编辑收获地址
func (m *defaultUser) EditUserReceiveAddress(ctx context.Context, in *UserReceiveAddressEditRequest, opts ...grpc.CallOption) (*UserReceiveAddressEditResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.EditUserReceiveAddress(ctx, in, opts...)
}

// 删除收获地址
func (m *defaultUser) DelUserReceiveAddress(ctx context.Context, in *UserReceiveAddressDelRequest, opts ...grpc.CallOption) (*UserReceiveAddressDelResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DelUserReceiveAddress(ctx, in, opts...)
}

// 获取收获地址列表
func (m *defaultUser) GetUserReceiveAddressList(ctx context.Context, in *UserReceiveAddressListRequest, opts ...grpc.CallOption) (*UserReceiveAddressListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserReceiveAddressList(ctx, in, opts...)
}

// 添加收藏
func (m *defaultUser) AddUserCollection(ctx context.Context, in *UserCollectionAddRequest, opts ...grpc.CallOption) (*UserCollectionAddResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddUserCollection(ctx, in, opts...)
}

// 删除收藏
func (m *defaultUser) DelUserCollection(ctx context.Context, in *UserCollectionDelRequest, opts ...grpc.CallOption) (*UserCollectionDelResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DelUserCollection(ctx, in, opts...)
}

// 收藏列表
func (m *defaultUser) GetUserCollectionList(ctx context.Context, in *UserCollectionListRequest, opts ...grpc.CallOption) (*UserCollectionListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserCollectionList(ctx, in, opts...)
}

// 根据主键id,查询收获地址
func (m *defaultUser) GetUserReceiveAddressInfo(ctx context.Context, in *UserReceiveAddressInfoRequest, opts ...grpc.CallOption) (*UserReceiveAddress, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserReceiveAddressInfo(ctx, in, opts...)
}
