// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: cart.proto

package cartclient

import (
	"context"

	"github.com/wansui976/go_zero_shop/apps/cart/rpc/cart"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CartItem          = cart.CartItem
	CartItemRequest   = cart.CartItemRequest
	CartListRequest   = cart.CartListRequest
	CartListResponse  = cart.CartListResponse
	DeleteCartRequest = cart.DeleteCartRequest
	Response          = cart.Response
	UpdateCartRequest = cart.UpdateCartRequest

	Cart interface {
		// 添加购物车（已存在则更新数量）
		AddCart(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*Response, error)
		// 获取用户购物车列表（过滤删除状态为0的项）
		GetCartList(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*CartListResponse, error)
		// 更新购物车（支持修改数量/选中状态）
		UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*Response, error)
		// 删除购物车项（逻辑删除：置delete_status=1）
		DeleteCart(ctx context.Context, in *DeleteCartRequest, opts ...grpc.CallOption) (*Response, error)
		// 清空用户购物车（批量置delete_status=1）
		ClearCart(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*Response, error)
		// 切换购物车商品选中状态（单独封装便于前端调用）
		CheckCart(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*Response, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

// 添加购物车（已存在则更新数量）
func (m *defaultCart) AddCart(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*Response, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.AddCart(ctx, in, opts...)
}

// 获取用户购物车列表（过滤删除状态为0的项）
func (m *defaultCart) GetCartList(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*CartListResponse, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.GetCartList(ctx, in, opts...)
}

// 更新购物车（支持修改数量/选中状态）
func (m *defaultCart) UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*Response, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.UpdateCart(ctx, in, opts...)
}

// 删除购物车项（逻辑删除：置delete_status=1）
func (m *defaultCart) DeleteCart(ctx context.Context, in *DeleteCartRequest, opts ...grpc.CallOption) (*Response, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.DeleteCart(ctx, in, opts...)
}

// 清空用户购物车（批量置delete_status=1）
func (m *defaultCart) ClearCart(ctx context.Context, in *CartListRequest, opts ...grpc.CallOption) (*Response, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.ClearCart(ctx, in, opts...)
}

// 切换购物车商品选中状态（单独封装便于前端调用）
func (m *defaultCart) CheckCart(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*Response, error) {
	client := cart.NewCartClient(m.cli.Conn())
	return client.CheckCart(ctx, in, opts...)
}
