// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: order.proto

package orderservice

import (
	"context"

	"github.com/wansui976/go_zero_shop/apps/order/rpc/apps/order/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddOrderRequest               = order.AddOrderRequest
	AddOrderResponse              = order.AddOrderResponse
	CreateOrderDTMConfirmRequest  = order.CreateOrderDTMConfirmRequest
	CreateOrderDTMConfirmResponse = order.CreateOrderDTMConfirmResponse
	CreateOrderDTMRevertRequest   = order.CreateOrderDTMRevertRequest
	CreateOrderDTMRevertResponse  = order.CreateOrderDTMRevertResponse
	CreateOrderRequest            = order.CreateOrderRequest
	CreateOrderResponse           = order.CreateOrderResponse
	GetOrderByIdRequest           = order.GetOrderByIdRequest
	GetOrderByIdResponse          = order.GetOrderByIdResponse
	OrderBase                     = order.OrderBase
	OrderDetail                   = order.OrderDetail
	OrderProductItem              = order.OrderProductItem
	OrdersRequest                 = order.OrdersRequest
	OrdersResponse                = order.OrdersResponse
	ReceiverInfo                  = order.ReceiverInfo

	OrderService interface {
		// 查询订单列表
		Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
		// 查询订单详情
		GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*GetOrderByIdResponse, error)
		// 普通下单（可选择是否走 DTM）
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		// 订单预检（库存检查等）
		CreateOrderCheck(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		// 订单回滚（普通下单失败兜底）
		RollbackOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		// Try：创建半成品订单
		CreateOrderDTM(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error)
		// Confirm：确认订单（扣库存 + 改状态）
		CreateOrderDTMConfirm(ctx context.Context, in *CreateOrderDTMConfirmRequest, opts ...grpc.CallOption) (*CreateOrderDTMConfirmResponse, error)
		// Cancel：回滚订单
		CreateOrderDTMRevert(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// 查询订单列表
func (m *defaultOrderService) Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.Orders(ctx, in, opts...)
}

// 查询订单详情
func (m *defaultOrderService) GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*GetOrderByIdResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetOrderById(ctx, in, opts...)
}

// 普通下单（可选择是否走 DTM）
func (m *defaultOrderService) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// 订单预检（库存检查等）
func (m *defaultOrderService) CreateOrderCheck(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrderCheck(ctx, in, opts...)
}

// 订单回滚（普通下单失败兜底）
func (m *defaultOrderService) RollbackOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.RollbackOrder(ctx, in, opts...)
}

// Try：创建半成品订单
func (m *defaultOrderService) CreateOrderDTM(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrderDTM(ctx, in, opts...)
}

// Confirm：确认订单（扣库存 + 改状态）
func (m *defaultOrderService) CreateOrderDTMConfirm(ctx context.Context, in *CreateOrderDTMConfirmRequest, opts ...grpc.CallOption) (*CreateOrderDTMConfirmResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrderDTMConfirm(ctx, in, opts...)
}

// Cancel：回滚订单
func (m *defaultOrderService) CreateOrderDTMRevert(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrderDTMRevert(ctx, in, opts...)
}
