apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: go-zero-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.76.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 14268
          name: collector
        - containerPort: 6831
          protocol: UDP
          name: compact-thrift
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        startupProbe:
          tcpSocket:
            port: 14268
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          tcpSocket:
            port: 14268
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 14268
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: go-zero-shop
spec:
  selector:
    app: jaeger
  ports:
  - port: 16686
    targetPort: 16686
    name: ui
  - port: 14268
    targetPort: 14268
    name: collector
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: compact-thrift
  type: ClusterIP
