// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品状态枚举
type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_UNKNOWN ProductStatus = 0 // 未知状态（默认值）
	ProductStatus_PRODUCT_STATUS_OFFLINE ProductStatus = 1 // 下架
	ProductStatus_PRODUCT_STATUS_ONLINE  ProductStatus = 2 // 上架
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_UNKNOWN",
		1: "PRODUCT_STATUS_OFFLINE",
		2: "PRODUCT_STATUS_ONLINE",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_UNKNOWN": 0,
		"PRODUCT_STATUS_OFFLINE": 1,
		"PRODUCT_STATUS_ONLINE":  2,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_product_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_product_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

type ProductItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductItemRequest) Reset() {
	*x = ProductItemRequest{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItemRequest) ProtoMessage() {}

func (x *ProductItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItemRequest.ProtoReflect.Descriptor instead.
func (*ProductItemRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    string                 `protobuf:"bytes,1,opt,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRequest) GetProductIds() string {
	if x != nil {
		return x.ProductIds
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      map[int64]*ProductItem `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductResponse) GetProducts() map[int64]*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Ps            int32                  `protobuf:"varint,3,opt,name=ps,proto3" json:"ps,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListRequest) Reset() {
	*x = ProductListRequest{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListRequest) ProtoMessage() {}

func (x *ProductListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListRequest.ProtoReflect.Descriptor instead.
func (*ProductListRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductListRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductListRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ProductListRequest) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

func (x *ProductListRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ProductListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnd         bool                   `protobuf:"varint,1,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Products      []*ProductItem         `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListResponse) Reset() {
	*x = ProductListResponse{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListResponse) ProtoMessage() {}

func (x *ProductListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListResponse.ProtoReflect.Descriptor instead.
func (*ProductListResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductListResponse) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

func (x *ProductListResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProductListResponse) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductListResponse) GetProducts() []*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductAllListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAllListRequest) Reset() {
	*x = ProductAllListRequest{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAllListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAllListRequest) ProtoMessage() {}

func (x *ProductAllListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAllListRequest.ProtoReflect.Descriptor instead.
func (*ProductAllListRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

type ProductAllListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductItem         `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAllListResponse) Reset() {
	*x = ProductAllListResponse{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAllListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAllListResponse) ProtoMessage() {}

func (x *ProductAllListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAllListResponse.ProtoReflect.Descriptor instead.
func (*ProductAllListResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductAllListResponse) GetProducts() []*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type OperationProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationProductsRequest) Reset() {
	*x = OperationProductsRequest{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationProductsRequest) ProtoMessage() {}

func (x *OperationProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationProductsRequest.ProtoReflect.Descriptor instead.
func (*OperationProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

type OperationProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductItem         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationProductsResponse) Reset() {
	*x = OperationProductsResponse{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationProductsResponse) ProtoMessage() {}

func (x *OperationProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationProductsResponse.ProtoReflect.Descriptor instead.
func (*OperationProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *OperationProductsResponse) GetProducts() []*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type DecrProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrProduct) Reset() {
	*x = DecrProduct{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrProduct) ProtoMessage() {}

func (x *DecrProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrProduct.ProtoReflect.Descriptor instead.
func (*DecrProduct) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *DecrProduct) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DecrProduct) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ProductItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ===== 基本信息 =====
	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                            // 商品ID (SPU)
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         // 商品名称
	Brief    string `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief,omitempty"`                       // 简介
	Keywords string `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`                 // 关键词，用于搜索
	ImageUrl string `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // 主图URL
	// ===== 分类与品牌 =====
	CategoryId     int64  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`              // 主分类ID
	CategoryName   string `protobuf:"bytes,7,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`         // 主分类名称
	CategoryIdList string `protobuf:"bytes,8,opt,name=category_id_list,json=categoryIdList,proto3" json:"category_id_list,omitempty"` // 所有分类ID集合（逗号分隔，如“1,2,3”）
	BrandId        int64  `protobuf:"varint,9,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`                       // 品牌ID
	BrandName      string `protobuf:"bytes,10,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`                 // 品牌名称
	// ===== 价格与库存 =====
	Price    int64 `protobuf:"varint,11,opt,name=price,proto3" json:"price,omitempty"`                       // 售价（元）
	Stock    int64 `protobuf:"varint,12,opt,name=stock,proto3" json:"stock,omitempty"`                       // 当前库存数量
	LowStock int32 `protobuf:"varint,13,opt,name=low_stock,json=lowStock,proto3" json:"low_stock,omitempty"` // 库存预警值（低于此值提示补货）
	Sales    int32 `protobuf:"varint,14,opt,name=sales,proto3" json:"sales,omitempty"`                       // 累计销量
	// ===== 物理属性 =====
	Unit   string  `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`       // 销售单位（件 / 台 / 箱）
	Weight float32 `protobuf:"fixed32,16,opt,name=weight,proto3" json:"weight,omitempty"` // 商品重量（kg）
	// ===== 内容描述 =====
	DetailTitle string `protobuf:"bytes,17,opt,name=detail_title,json=detailTitle,proto3" json:"detail_title,omitempty"` // 详情页标题
	DetailDesc  string `protobuf:"bytes,18,opt,name=detail_desc,json=detailDesc,proto3" json:"detail_desc,omitempty"`    // 详情页简洁描述
	DetailHtml  string `protobuf:"bytes,19,opt,name=detail_html,json=detailHtml,proto3" json:"detail_html,omitempty"`    // 富文本详情内容（HTML格式）
	// ===== 状态与控制 =====
	Sort                int32         `protobuf:"varint,20,opt,name=sort,proto3" json:"sort,omitempty"`                                                            // 全局排序值（值越大越靠前）
	NewStatusSort       int32         `protobuf:"varint,21,opt,name=new_status_sort,json=newStatusSort,proto3" json:"new_status_sort,omitempty"`                   // 新品排序值（值越大越新，越靠前）
	RecommendStatusSort int32         `protobuf:"varint,22,opt,name=recommend_status_sort,json=recommendStatusSort,proto3" json:"recommend_status_sort,omitempty"` // 推荐排序值（值越大推荐优先级越高）
	Status              ProductStatus `protobuf:"varint,23,opt,name=status,proto3,enum=product.ProductStatus" json:"status,omitempty"`                             // 商品状态
	CreateTime          int64         `protobuf:"varint,24,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                              // 创建时间（时间戳，毫秒级）
	UpdateTime          int64         `protobuf:"varint,25,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                              // 更新时间（时间戳，毫秒级）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProductItem) Reset() {
	*x = ProductItem{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItem) ProtoMessage() {}

func (x *ProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItem.ProtoReflect.Descriptor instead.
func (*ProductItem) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *ProductItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductItem) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *ProductItem) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *ProductItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProductItem) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductItem) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ProductItem) GetCategoryIdList() string {
	if x != nil {
		return x.CategoryIdList
	}
	return ""
}

func (x *ProductItem) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ProductItem) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *ProductItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductItem) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductItem) GetLowStock() int32 {
	if x != nil {
		return x.LowStock
	}
	return 0
}

func (x *ProductItem) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *ProductItem) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductItem) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductItem) GetDetailTitle() string {
	if x != nil {
		return x.DetailTitle
	}
	return ""
}

func (x *ProductItem) GetDetailDesc() string {
	if x != nil {
		return x.DetailDesc
	}
	return ""
}

func (x *ProductItem) GetDetailHtml() string {
	if x != nil {
		return x.DetailHtml
	}
	return ""
}

func (x *ProductItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductItem) GetNewStatusSort() int32 {
	if x != nil {
		return x.NewStatusSort
	}
	return 0
}

func (x *ProductItem) GetRecommendStatusSort() int32 {
	if x != nil {
		return x.RecommendStatusSort
	}
	return 0
}

func (x *ProductItem) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNKNOWN
}

func (x *ProductItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ProductItem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// }
type UpdateProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockRequest) Reset() {
	*x = UpdateProductStockRequest{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockRequest) ProtoMessage() {}

func (x *UpdateProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductStockRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProductStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductStockRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UpdateProductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockResponse) Reset() {
	*x = UpdateProductStockResponse{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockResponse) ProtoMessage() {}

func (x *UpdateProductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductStockResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

type CheckAndUpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndUpdateStockRequest) Reset() {
	*x = CheckAndUpdateStockRequest{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndUpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndUpdateStockRequest) ProtoMessage() {}

func (x *CheckAndUpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndUpdateStockRequest.ProtoReflect.Descriptor instead.
func (*CheckAndUpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *CheckAndUpdateStockRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckAndUpdateStockRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CheckAndUpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndUpdateStockResponse) Reset() {
	*x = CheckAndUpdateStockResponse{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndUpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndUpdateStockResponse) ProtoMessage() {}

func (x *CheckAndUpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndUpdateStockResponse.ProtoReflect.Descriptor instead.
func (*CheckAndUpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *CheckAndUpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DecrStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DecrProduct         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrStockRequest) Reset() {
	*x = DecrStockRequest{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrStockRequest) ProtoMessage() {}

func (x *DecrStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrStockRequest.ProtoReflect.Descriptor instead.
func (*DecrStockRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *DecrStockRequest) GetItems() []*DecrProduct {
	if x != nil {
		return x.Items
	}
	return nil
}

type DecrStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrStockResponse) Reset() {
	*x = DecrStockResponse{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrStockResponse) ProtoMessage() {}

func (x *DecrStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrStockResponse.ProtoReflect.Descriptor instead.
func (*DecrStockResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\"3\n" +
	"\x12ProductItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"1\n" +
	"\x0eProductRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x01(\tR\n" +
	"productIds\"\xa8\x01\n" +
	"\x0fProductResponse\x12B\n" +
	"\bproducts\x18\x01 \x03(\v2&.product.ProductResponse.ProductsEntryR\bproducts\x1aQ\n" +
	"\rProductsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.product.ProductItemR\x05value:\x028\x01\"|\n" +
	"\x12ProductListRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x0e\n" +
	"\x02ps\x18\x03 \x01(\x05R\x02ps\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\"\x9b\x01\n" +
	"\x13ProductListResponse\x12\x15\n" +
	"\x06is_end\x18\x01 \x01(\bR\x05isEnd\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x120\n" +
	"\bproducts\x18\x04 \x03(\v2\x14.product.ProductItemR\bproducts\"\x17\n" +
	"\x15ProductAllListRequest\"J\n" +
	"\x16ProductAllListResponse\x120\n" +
	"\bproducts\x18\x04 \x03(\v2\x14.product.ProductItemR\bproducts\"\x1a\n" +
	"\x18OperationProductsRequest\"M\n" +
	"\x19OperationProductsResponse\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.product.ProductItemR\bproducts\"/\n" +
	"\vDecrProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\xfc\x05\n" +
	"\vProductItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brief\x18\x03 \x01(\tR\x05brief\x12\x1a\n" +
	"\bkeywords\x18\x04 \x01(\tR\bkeywords\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\a \x01(\tR\fcategoryName\x12(\n" +
	"\x10category_id_list\x18\b \x01(\tR\x0ecategoryIdList\x12\x19\n" +
	"\bbrand_id\x18\t \x01(\x03R\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\n" +
	" \x01(\tR\tbrandName\x12\x14\n" +
	"\x05price\x18\v \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\f \x01(\x03R\x05stock\x12\x1b\n" +
	"\tlow_stock\x18\r \x01(\x05R\blowStock\x12\x14\n" +
	"\x05sales\x18\x0e \x01(\x05R\x05sales\x12\x12\n" +
	"\x04unit\x18\x0f \x01(\tR\x04unit\x12\x16\n" +
	"\x06weight\x18\x10 \x01(\x02R\x06weight\x12!\n" +
	"\fdetail_title\x18\x11 \x01(\tR\vdetailTitle\x12\x1f\n" +
	"\vdetail_desc\x18\x12 \x01(\tR\n" +
	"detailDesc\x12\x1f\n" +
	"\vdetail_html\x18\x13 \x01(\tR\n" +
	"detailHtml\x12\x12\n" +
	"\x04sort\x18\x14 \x01(\x05R\x04sort\x12&\n" +
	"\x0fnew_status_sort\x18\x15 \x01(\x05R\rnewStatusSort\x122\n" +
	"\x15recommend_status_sort\x18\x16 \x01(\x05R\x13recommendStatusSort\x12.\n" +
	"\x06status\x18\x17 \x01(\x0e2\x16.product.ProductStatusR\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x18 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x19 \x01(\x03R\n" +
	"updateTime\"L\n" +
	"\x19UpdateProductStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\x1c\n" +
	"\x1aUpdateProductStockResponse\"Z\n" +
	"\x1aCheckAndUpdateStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"7\n" +
	"\x1bCheckAndUpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\x10DecrStockRequest\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.product.DecrProductR\x05items\"\x13\n" +
	"\x11DecrStockResponse*b\n" +
	"\rProductStatus\x12\x1a\n" +
	"\x16PRODUCT_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16PRODUCT_STATUS_OFFLINE\x10\x01\x12\x19\n" +
	"\x15PRODUCT_STATUS_ONLINE\x10\x022\x8d\a\n" +
	"\aProduct\x12<\n" +
	"\aProduct\x12\x1b.product.ProductItemRequest\x1a\x14.product.ProductItem\x12=\n" +
	"\bProducts\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12H\n" +
	"\vProductList\x12\x1b.product.ProductListRequest\x1a\x1c.product.ProductListResponse\x12Q\n" +
	"\x0eProductAllList\x12\x1e.product.ProductAllListRequest\x1a\x1f.product.ProductAllListResponse\x12Z\n" +
	"\x11OperationProducts\x12!.product.OperationProductsRequest\x1a\".product.OperationProductsResponse\x12]\n" +
	"\x12UpdateProductStock\x12\".product.UpdateProductStockRequest\x1a#.product.UpdateProductStockResponse\x12`\n" +
	"\x13CheckAndUpdateStock\x12#.product.CheckAndUpdateStockRequest\x1a$.product.CheckAndUpdateStockResponse\x12\\\n" +
	"\x11CheckProductStock\x12\".product.UpdateProductStockRequest\x1a#.product.UpdateProductStockResponse\x12_\n" +
	"\x14RollbackProductStock\x12\".product.UpdateProductStockRequest\x1a#.product.UpdateProductStockResponse\x12B\n" +
	"\tDecrStock\x12\x19.product.DecrStockRequest\x1a\x1a.product.DecrStockResponse\x12H\n" +
	"\x0fDecrStockRevert\x12\x19.product.DecrStockRequest\x1a\x1a.product.DecrStockResponseB\vZ\t./productb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_product_proto_goTypes = []any{
	(ProductStatus)(0),                  // 0: product.ProductStatus
	(*ProductItemRequest)(nil),          // 1: product.ProductItemRequest
	(*ProductRequest)(nil),              // 2: product.ProductRequest
	(*ProductResponse)(nil),             // 3: product.ProductResponse
	(*ProductListRequest)(nil),          // 4: product.ProductListRequest
	(*ProductListResponse)(nil),         // 5: product.ProductListResponse
	(*ProductAllListRequest)(nil),       // 6: product.ProductAllListRequest
	(*ProductAllListResponse)(nil),      // 7: product.ProductAllListResponse
	(*OperationProductsRequest)(nil),    // 8: product.OperationProductsRequest
	(*OperationProductsResponse)(nil),   // 9: product.OperationProductsResponse
	(*DecrProduct)(nil),                 // 10: product.DecrProduct
	(*ProductItem)(nil),                 // 11: product.ProductItem
	(*UpdateProductStockRequest)(nil),   // 12: product.UpdateProductStockRequest
	(*UpdateProductStockResponse)(nil),  // 13: product.UpdateProductStockResponse
	(*CheckAndUpdateStockRequest)(nil),  // 14: product.CheckAndUpdateStockRequest
	(*CheckAndUpdateStockResponse)(nil), // 15: product.CheckAndUpdateStockResponse
	(*DecrStockRequest)(nil),            // 16: product.DecrStockRequest
	(*DecrStockResponse)(nil),           // 17: product.DecrStockResponse
	nil,                                 // 18: product.ProductResponse.ProductsEntry
}
var file_product_proto_depIdxs = []int32{
	18, // 0: product.ProductResponse.products:type_name -> product.ProductResponse.ProductsEntry
	11, // 1: product.ProductListResponse.products:type_name -> product.ProductItem
	11, // 2: product.ProductAllListResponse.products:type_name -> product.ProductItem
	11, // 3: product.OperationProductsResponse.products:type_name -> product.ProductItem
	0,  // 4: product.ProductItem.status:type_name -> product.ProductStatus
	10, // 5: product.DecrStockRequest.items:type_name -> product.DecrProduct
	11, // 6: product.ProductResponse.ProductsEntry.value:type_name -> product.ProductItem
	1,  // 7: product.Product.Product:input_type -> product.ProductItemRequest
	2,  // 8: product.Product.Products:input_type -> product.ProductRequest
	4,  // 9: product.Product.ProductList:input_type -> product.ProductListRequest
	6,  // 10: product.Product.ProductAllList:input_type -> product.ProductAllListRequest
	8,  // 11: product.Product.OperationProducts:input_type -> product.OperationProductsRequest
	12, // 12: product.Product.UpdateProductStock:input_type -> product.UpdateProductStockRequest
	14, // 13: product.Product.CheckAndUpdateStock:input_type -> product.CheckAndUpdateStockRequest
	12, // 14: product.Product.CheckProductStock:input_type -> product.UpdateProductStockRequest
	12, // 15: product.Product.RollbackProductStock:input_type -> product.UpdateProductStockRequest
	16, // 16: product.Product.DecrStock:input_type -> product.DecrStockRequest
	16, // 17: product.Product.DecrStockRevert:input_type -> product.DecrStockRequest
	11, // 18: product.Product.Product:output_type -> product.ProductItem
	3,  // 19: product.Product.Products:output_type -> product.ProductResponse
	5,  // 20: product.Product.ProductList:output_type -> product.ProductListResponse
	7,  // 21: product.Product.ProductAllList:output_type -> product.ProductAllListResponse
	9,  // 22: product.Product.OperationProducts:output_type -> product.OperationProductsResponse
	13, // 23: product.Product.UpdateProductStock:output_type -> product.UpdateProductStockResponse
	15, // 24: product.Product.CheckAndUpdateStock:output_type -> product.CheckAndUpdateStockResponse
	13, // 25: product.Product.CheckProductStock:output_type -> product.UpdateProductStockResponse
	13, // 26: product.Product.RollbackProductStock:output_type -> product.UpdateProductStockResponse
	17, // 27: product.Product.DecrStock:output_type -> product.DecrStockResponse
	17, // 28: product.Product.DecrStockRevert:output_type -> product.DecrStockResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		EnumInfos:         file_product_proto_enumTypes,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
