// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: reply.proto

package replyclient

import (
	"context"

	"github.com/wansui976/go_zero_shop/apps/reply/rpc/reply"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentItem           = reply.CommentItem
	CommentsRequest       = reply.CommentsRequest
	CommentsResponse      = reply.CommentsResponse
	CreateCommentRequest  = reply.CreateCommentRequest
	CreateCommentResponse = reply.CreateCommentResponse
	DeleteCommentRequest  = reply.DeleteCommentRequest
	DeleteCommentResponse = reply.DeleteCommentResponse
	UpdateCommentRequest  = reply.UpdateCommentRequest
	UpdateCommentResponse = reply.UpdateCommentResponse

	Reply interface {
		CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
		DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
		UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
		Comments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

func (m *defaultReply) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

func (m *defaultReply) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

func (m *defaultReply) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.UpdateComment(ctx, in, opts...)
}

func (m *defaultReply) Comments(ctx context.Context, in *CommentsRequest, opts ...grpc.CallOption) (*CommentsResponse, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.Comments(ctx, in, opts...)
}
