// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderItemsFieldNames          = builder.RawFieldNames(&OrderItems{})
	orderItemsRows                = strings.Join(orderItemsFieldNames, ",")
	orderItemsRowsExpectAutoSet   = strings.Join(stringx.Remove(orderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderItemsRowsWithPlaceHolder = strings.Join(stringx.Remove(orderItemsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOrderItemsIdPrefix = "cache:orderItems:id:"
)

type (
	orderItemsModel interface {
		Insert(ctx context.Context, data *OrderItems) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OrderItems, error)
		Update(ctx context.Context, data *OrderItems) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderItemsModel struct {
		sqlc.CachedConn
		table string
	}

	OrderItems struct {
		Id         int64  `db:"id"`
		OrderId    string `db:"order_id"`    // 订单编号
		ProductId  int64  `db:"product_id"`  // 商品 ID
		Quantity   int64  `db:"quantity"`    // 数量
		UnitPrice  int64  `db:"unit_price"`  // 下单时单价
		TotalPrice int64  `db:"total_price"` // 该商品总价（=单价*数量）
		CreateTime int64  `db:"create_time"`
		UpdateTime int64  `db:"update_time"`
	}
)

func newOrderItemsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderItemsModel {
	return &defaultOrderItemsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order_items`",
	}
}

func (m *defaultOrderItemsModel) Delete(ctx context.Context, id int64) error {
	orderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderItemsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, orderItemsIdKey)
	return err
}

func (m *defaultOrderItemsModel) FindOne(ctx context.Context, id int64) (*OrderItems, error) {
	orderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderItemsIdPrefix, id)
	var resp OrderItems
	err := m.QueryRowCtx(ctx, &resp, orderItemsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderItemsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderItemsModel) Insert(ctx context.Context, data *OrderItems) (sql.Result, error) {
	orderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderItemsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, orderItemsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.Quantity, data.UnitPrice, data.TotalPrice)
	}, orderItemsIdKey)
	return ret, err
}

func (m *defaultOrderItemsModel) Update(ctx context.Context, data *OrderItems) error {
	orderItemsIdKey := fmt.Sprintf("%s%v", cacheOrderItemsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderItemsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OrderId, data.ProductId, data.Quantity, data.UnitPrice, data.TotalPrice, data.Id)
	}, orderItemsIdKey)
	return err
}

func (m *defaultOrderItemsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOrderItemsIdPrefix, primary)
}

func (m *defaultOrderItemsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderItemsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderItemsModel) tableName() string {
	return m.table
}
