// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderAddressSnapshotFieldNames          = builder.RawFieldNames(&OrderAddressSnapshot{})
	orderAddressSnapshotRows                = strings.Join(orderAddressSnapshotFieldNames, ",")
	orderAddressSnapshotRowsExpectAutoSet   = strings.Join(stringx.Remove(orderAddressSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderAddressSnapshotRowsWithPlaceHolder = strings.Join(stringx.Remove(orderAddressSnapshotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOrderAddressSnapshotIdPrefix = "cache:orderAddressSnapshot:id:"
)

type (
	orderAddressSnapshotModel interface {
		Insert(ctx context.Context, data *OrderAddressSnapshot) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OrderAddressSnapshot, error)
		Update(ctx context.Context, data *OrderAddressSnapshot) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderAddressSnapshotModel struct {
		sqlc.CachedConn
		table string
	}

	OrderAddressSnapshot struct {
		Id         int64     `db:"id"`
		OrderId    string    `db:"order_id"`
		UserId     int64     `db:"user_id"`
		Name       string    `db:"name"`
		Phone      string    `db:"phone"`
		Province   string    `db:"province"`
		City       string    `db:"city"`
		District   string    `db:"district"`
		Detail     string    `db:"detail"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newOrderAddressSnapshotModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrderAddressSnapshotModel {
	return &defaultOrderAddressSnapshotModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`order_address_snapshot`",
	}
}

func (m *defaultOrderAddressSnapshotModel) Delete(ctx context.Context, id int64) error {
	orderAddressSnapshotIdKey := fmt.Sprintf("%s%v", cacheOrderAddressSnapshotIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, orderAddressSnapshotIdKey)
	return err
}

func (m *defaultOrderAddressSnapshotModel) FindOne(ctx context.Context, id int64) (*OrderAddressSnapshot, error) {
	orderAddressSnapshotIdKey := fmt.Sprintf("%s%v", cacheOrderAddressSnapshotIdPrefix, id)
	var resp OrderAddressSnapshot
	err := m.QueryRowCtx(ctx, &resp, orderAddressSnapshotIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderAddressSnapshotRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderAddressSnapshotModel) Insert(ctx context.Context, data *OrderAddressSnapshot) (sql.Result, error) {
	orderAddressSnapshotIdKey := fmt.Sprintf("%s%v", cacheOrderAddressSnapshotIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderAddressSnapshotRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OrderId, data.UserId, data.Name, data.Phone, data.Province, data.City, data.District, data.Detail)
	}, orderAddressSnapshotIdKey)
	return ret, err
}

func (m *defaultOrderAddressSnapshotModel) Update(ctx context.Context, data *OrderAddressSnapshot) error {
	orderAddressSnapshotIdKey := fmt.Sprintf("%s%v", cacheOrderAddressSnapshotIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderAddressSnapshotRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OrderId, data.UserId, data.Name, data.Phone, data.Province, data.City, data.District, data.Detail, data.Id)
	}, orderAddressSnapshotIdKey)
	return err
}

func (m *defaultOrderAddressSnapshotModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOrderAddressSnapshotIdPrefix, primary)
}

func (m *defaultOrderAddressSnapshotModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderAddressSnapshotRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrderAddressSnapshotModel) tableName() string {
	return m.table
}
