// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: cart.proto

package server

import (
	"context"

	"github.com/wansui976/go_zero_shop/apps/cart/rpc/cart"
	"github.com/wansui976/go_zero_shop/apps/cart/rpc/internal/logic"
	"github.com/wansui976/go_zero_shop/apps/cart/rpc/internal/svc"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

// 添加购物车（已存在则更新数量）
func (s *CartServer) AddCart(ctx context.Context, in *cart.CartItemRequest) (*cart.Response, error) {
	l := logic.NewAddCartLogic(ctx, s.svcCtx)
	return l.AddCart(in)
}

// 获取用户购物车列表（过滤删除状态为0的项）
func (s *CartServer) GetCartList(ctx context.Context, in *cart.CartListRequest) (*cart.CartListResponse, error) {
	l := logic.NewGetCartListLogic(ctx, s.svcCtx)
	return l.GetCartList(in)
}

// 更新购物车（支持修改数量/选中状态）
func (s *CartServer) UpdateCart(ctx context.Context, in *cart.UpdateCartRequest) (*cart.Response, error) {
	l := logic.NewUpdateCartLogic(ctx, s.svcCtx)
	return l.UpdateCart(in)
}

// 删除购物车项（逻辑删除：置delete_status=1）
func (s *CartServer) DeleteCart(ctx context.Context, in *cart.DeleteCartRequest) (*cart.Response, error) {
	l := logic.NewDeleteCartLogic(ctx, s.svcCtx)
	return l.DeleteCart(in)
}

// 清空用户购物车（批量置delete_status=1）
func (s *CartServer) ClearCart(ctx context.Context, in *cart.CartListRequest) (*cart.Response, error) {
	l := logic.NewClearCartLogic(ctx, s.svcCtx)
	return l.ClearCart(in)
}

// 切换购物车商品选中状态（单独封装便于前端调用）
func (s *CartServer) CheckCart(ctx context.Context, in *cart.CartItemRequest) (*cart.Response, error) {
	l := logic.NewCheckCartLogic(ctx, s.svcCtx)
	return l.CheckCart(in)
}
