// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: apps/order/rpc/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =======================================
// Cursor 分页请求
// =======================================
type OrderStatus int32

const (
	OrderStatus_OrderStatusCanceled   OrderStatus = 0 // 已取消
	OrderStatus_OrderStatusPending    OrderStatus = 1 // 待支付
	OrderStatus_OrderStatusPaid       OrderStatus = 2 // 已支付
	OrderStatus_OrderStatusDelivering OrderStatus = 3 // 待发货
	OrderStatus_OrderStatusShipped    OrderStatus = 4 // 已发货
	OrderStatus_OrderStatusReceived   OrderStatus = 5 // 待收货
	OrderStatus_OrderStatusCompleted  OrderStatus = 6 // 已完成
	OrderStatus_OrderStatusRefunding  OrderStatus = 7 // 退款中
	OrderStatus_OrderStatusRefunded   OrderStatus = 8 // 已退款
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "OrderStatusCanceled",
		1: "OrderStatusPending",
		2: "OrderStatusPaid",
		3: "OrderStatusDelivering",
		4: "OrderStatusShipped",
		5: "OrderStatusReceived",
		6: "OrderStatusCompleted",
		7: "OrderStatusRefunding",
		8: "OrderStatusRefunded",
	}
	OrderStatus_value = map[string]int32{
		"OrderStatusCanceled":   0,
		"OrderStatusPending":    1,
		"OrderStatusPaid":       2,
		"OrderStatusDelivering": 3,
		"OrderStatusShipped":    4,
		"OrderStatusReceived":   5,
		"OrderStatusCompleted":  6,
		"OrderStatusRefunding":  7,
		"OrderStatusRefunded":   8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_order_rpc_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_apps_order_rpc_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{0}
}

type PaymentType int32

const (
	PaymentType_PAYMENT_UNKNOWN PaymentType = 0 // 默认值
	PaymentType_PAYMENT_WECHAT  PaymentType = 1 // 微信支付
	PaymentType_PAYMENT_ALIPAY  PaymentType = 2 // 支付宝支付
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "PAYMENT_UNKNOWN",
		1: "PAYMENT_WECHAT",
		2: "PAYMENT_ALIPAY",
	}
	PaymentType_value = map[string]int32{
		"PAYMENT_UNKNOWN": 0,
		"PAYMENT_WECHAT":  1,
		"PAYMENT_ALIPAY":  2,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_order_rpc_order_proto_enumTypes[1].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_apps_order_rpc_order_proto_enumTypes[1]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{1}
}

type OrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"` // 订单状态（见 OrderStatus 枚举：0=已取消,1=待支付,2=已支付,...）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersRequest) Reset() {
	*x = OrdersRequest{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersRequest) ProtoMessage() {}

func (x *OrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersRequest.ProtoReflect.Descriptor instead.
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrdersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_OrderStatusCanceled
}

// 分页响应
type OrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderIds      []int64                `protobuf:"varint,1,rep,packed,name=orderIds,proto3" json:"orderIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersResponse) Reset() {
	*x = OrdersResponse{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersResponse) ProtoMessage() {}

func (x *OrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersResponse.ProtoReflect.Descriptor instead.
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrdersResponse) GetOrderIds() []int64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

type OrderProductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProductItem) Reset() {
	*x = OrderProductItem{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductItem) ProtoMessage() {}

func (x *OrderProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductItem.ProtoReflect.Descriptor instead.
func (*OrderProductItem) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderProductItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProductItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 公共：订单基础信息
type OrderBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBase) Reset() {
	*x = OrderBase{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBase) ProtoMessage() {}

func (x *OrderBase) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBase.ProtoReflect.Descriptor instead.
func (*OrderBase) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderBase) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderBase) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderBase) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderBase) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_OrderStatusCanceled
}

func (x *OrderBase) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OrderBase) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 公共：收货地址信息
type ReceiverInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReceiverName    string                 `protobuf:"bytes,1,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone   string                 `protobuf:"bytes,2,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,3,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReceiverInfo) Reset() {
	*x = ReceiverInfo{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverInfo) ProtoMessage() {}

func (x *ReceiverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverInfo.ProtoReflect.Descriptor instead.
func (*ReceiverInfo) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiverInfo) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *ReceiverInfo) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *ReceiverInfo) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

type OrderDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *OrderBase             `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`                                                          // 基础信息
	Products      []*OrderProductItem    `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`                                                  // 商品列表
	Receiver      *ReceiverInfo          `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`                                                  // 收货地址
	PaymentAmount int64                  `protobuf:"varint,4,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`                  // 支付金额（分）
	PaymentType   PaymentType            `protobuf:"varint,5,opt,name=payment_type,json=paymentType,proto3,enum=order.PaymentType" json:"payment_type,omitempty"` // 支付类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderDetail) GetBase() *OrderBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *OrderDetail) GetProducts() []*OrderProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *OrderDetail) GetReceiver() *ReceiverInfo {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *OrderDetail) GetPaymentAmount() int64 {
	if x != nil {
		return x.PaymentAmount
	}
	return 0
}

func (x *OrderDetail) GetPaymentType() PaymentType {
	if x != nil {
		return x.PaymentType
	}
	return PaymentType_PAYMENT_UNKNOWN
}

// =======================================
// 查询订单详情
// =======================================
type GetOrderByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdRequest) Reset() {
	*x = GetOrderByIdRequest{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdRequest) ProtoMessage() {}

func (x *GetOrderByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIdRequest) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderDetail           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIdResponse) Reset() {
	*x = GetOrderByIdResponse{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIdResponse) ProtoMessage() {}

func (x *GetOrderByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIdResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIdResponse) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderByIdResponse) GetOrder() *OrderDetail {
	if x != nil {
		return x.Order
	}
	return nil
}

// =======================================
// 普通下单接口
// =======================================
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderProductItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"` // 多商品下单
	AddressId     int64                  `protobuf:"varint,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	UseDtm        bool                   `protobuf:"varint,4,opt,name=use_dtm,json=useDtm,proto3" json:"use_dtm,omitempty"` // 是否走分布式事务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*OrderProductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *CreateOrderRequest) GetUseDtm() bool {
	if x != nil {
		return x.UseDtm
	}
	return false
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// =======================================
// DTM：Try
// =======================================
type AddOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderProductItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	AddressId     int64                  `protobuf:"varint,4,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Gid           string                 `protobuf:"bytes,5,opt,name=gid,proto3" json:"gid,omitempty"`
	PaymentType   int64                  `protobuf:"varint,6,opt,name=PaymentType,proto3" json:"PaymentType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderRequest) Reset() {
	*x = AddOrderRequest{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderRequest) ProtoMessage() {}

func (x *AddOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderRequest.ProtoReflect.Descriptor instead.
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{10}
}

func (x *AddOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddOrderRequest) GetItems() []*OrderProductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AddOrderRequest) GetAddressId() int64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

func (x *AddOrderRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *AddOrderRequest) GetPaymentType() int64 {
	if x != nil {
		return x.PaymentType
	}
	return 0
}

type AddOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderResponse) Reset() {
	*x = AddOrderResponse{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderResponse) ProtoMessage() {}

func (x *AddOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderResponse.ProtoReflect.Descriptor instead.
func (*AddOrderResponse) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{11}
}

// =======================================
// DTM：Confirm
// =======================================
type CreateOrderDTMConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Gid           string                 `protobuf:"bytes,2,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderDTMConfirmRequest) Reset() {
	*x = CreateOrderDTMConfirmRequest{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderDTMConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderDTMConfirmRequest) ProtoMessage() {}

func (x *CreateOrderDTMConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderDTMConfirmRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderDTMConfirmRequest) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrderDTMConfirmRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderDTMConfirmRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type CreateOrderDTMConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderDTMConfirmResponse) Reset() {
	*x = CreateOrderDTMConfirmResponse{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderDTMConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderDTMConfirmResponse) ProtoMessage() {}

func (x *CreateOrderDTMConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderDTMConfirmResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderDTMConfirmResponse) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrderDTMConfirmResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// =======================================
// DTM：Cancel
// =======================================
type CreateOrderDTMRevertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gid           string                 `protobuf:"bytes,3,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderDTMRevertRequest) Reset() {
	*x = CreateOrderDTMRevertRequest{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderDTMRevertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderDTMRevertRequest) ProtoMessage() {}

func (x *CreateOrderDTMRevertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderDTMRevertRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderDTMRevertRequest) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOrderDTMRevertRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderDTMRevertRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderDTMRevertRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type CreateOrderDTMRevertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderDTMRevertResponse) Reset() {
	*x = CreateOrderDTMRevertResponse{}
	mi := &file_apps_order_rpc_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderDTMRevertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderDTMRevertResponse) ProtoMessage() {}

func (x *CreateOrderDTMRevertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_order_rpc_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderDTMRevertResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderDTMRevertResponse) Descriptor() ([]byte, []int) {
	return file_apps_order_rpc_order_proto_rawDescGZIP(), []int{15}
}

func (x *CreateOrderDTMRevertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apps_order_rpc_order_proto protoreflect.FileDescriptor

const file_apps_order_rpc_order_proto_rawDesc = "" +
	"\n" +
	"\x1aapps/order/rpc/order.proto\x12\x05order\"T\n" +
	"\rOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\",\n" +
	"\x0eOrdersResponse\x12\x1a\n" +
	"\borderIds\x18\x01 \x03(\x03R\borderIds\"M\n" +
	"\x10OrderProductItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"\xbd\x01\n" +
	"\tOrderBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x06 \x01(\x03R\n" +
	"updateTime\"\x85\x01\n" +
	"\fReceiverInfo\x12#\n" +
	"\rreceiver_name\x18\x01 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x02 \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\x03 \x01(\tR\x0freceiverAddress\"\xf7\x01\n" +
	"\vOrderDetail\x12$\n" +
	"\x04base\x18\x01 \x01(\v2\x10.order.OrderBaseR\x04base\x123\n" +
	"\bproducts\x18\x02 \x03(\v2\x17.order.OrderProductItemR\bproducts\x12/\n" +
	"\breceiver\x18\x03 \x01(\v2\x13.order.ReceiverInfoR\breceiver\x12%\n" +
	"\x0epayment_amount\x18\x04 \x01(\x03R\rpaymentAmount\x125\n" +
	"\fpayment_type\x18\x05 \x01(\x0e2\x12.order.PaymentTypeR\vpaymentType\"%\n" +
	"\x13GetOrderByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x14GetOrderByIdResponse\x12(\n" +
	"\x05order\x18\x01 \x01(\v2\x12.order.OrderDetailR\x05order\"\x94\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.order.OrderProductItemR\x05items\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\x03R\taddressId\x12\x17\n" +
	"\ause_dtm\x18\x04 \x01(\bR\x06useDtm\"d\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xac\x01\n" +
	"\x0fAddOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.order.OrderProductItemR\x05items\x12\x1d\n" +
	"\n" +
	"address_id\x18\x04 \x01(\x03R\taddressId\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\tR\x03gid\x12 \n" +
	"\vPaymentType\x18\x06 \x01(\x03R\vPaymentType\"\x12\n" +
	"\x10AddOrderResponse\"K\n" +
	"\x1cCreateOrderDTMConfirmRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x10\n" +
	"\x03gid\x18\x02 \x01(\tR\x03gid\"9\n" +
	"\x1dCreateOrderDTMConfirmResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x1bCreateOrderDTMRevertRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\tR\x03gid\"8\n" +
	"\x1cCreateOrderDTMRevertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xec\x01\n" +
	"\vOrderStatus\x12\x17\n" +
	"\x13OrderStatusCanceled\x10\x00\x12\x16\n" +
	"\x12OrderStatusPending\x10\x01\x12\x13\n" +
	"\x0fOrderStatusPaid\x10\x02\x12\x19\n" +
	"\x15OrderStatusDelivering\x10\x03\x12\x16\n" +
	"\x12OrderStatusShipped\x10\x04\x12\x17\n" +
	"\x13OrderStatusReceived\x10\x05\x12\x18\n" +
	"\x14OrderStatusCompleted\x10\x06\x12\x18\n" +
	"\x14OrderStatusRefunding\x10\a\x12\x17\n" +
	"\x13OrderStatusRefunded\x10\b*J\n" +
	"\vPaymentType\x12\x13\n" +
	"\x0fPAYMENT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0ePAYMENT_WECHAT\x10\x01\x12\x12\n" +
	"\x0ePAYMENT_ALIPAY\x10\x022\xd7\x04\n" +
	"\fOrderService\x125\n" +
	"\x06Orders\x12\x14.order.OrdersRequest\x1a\x15.order.OrdersResponse\x12G\n" +
	"\fGetOrderById\x12\x1a.order.GetOrderByIdRequest\x1a\x1b.order.GetOrderByIdResponse\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12I\n" +
	"\x10CreateOrderCheck\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12F\n" +
	"\rRollbackOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12A\n" +
	"\x0eCreateOrderDTM\x12\x16.order.AddOrderRequest\x1a\x17.order.AddOrderResponse\x12b\n" +
	"\x15CreateOrderDTMConfirm\x12#.order.CreateOrderDTMConfirmRequest\x1a$.order.CreateOrderDTMConfirmResponse\x12G\n" +
	"\x14CreateOrderDTMRevert\x12\x16.order.AddOrderRequest\x1a\x17.order.AddOrderResponseB\tZ\a./orderb\x06proto3"

var (
	file_apps_order_rpc_order_proto_rawDescOnce sync.Once
	file_apps_order_rpc_order_proto_rawDescData []byte
)

func file_apps_order_rpc_order_proto_rawDescGZIP() []byte {
	file_apps_order_rpc_order_proto_rawDescOnce.Do(func() {
		file_apps_order_rpc_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_order_rpc_order_proto_rawDesc), len(file_apps_order_rpc_order_proto_rawDesc)))
	})
	return file_apps_order_rpc_order_proto_rawDescData
}

var file_apps_order_rpc_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apps_order_rpc_order_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apps_order_rpc_order_proto_goTypes = []any{
	(OrderStatus)(0),                      // 0: order.OrderStatus
	(PaymentType)(0),                      // 1: order.PaymentType
	(*OrdersRequest)(nil),                 // 2: order.OrdersRequest
	(*OrdersResponse)(nil),                // 3: order.OrdersResponse
	(*OrderProductItem)(nil),              // 4: order.OrderProductItem
	(*OrderBase)(nil),                     // 5: order.OrderBase
	(*ReceiverInfo)(nil),                  // 6: order.ReceiverInfo
	(*OrderDetail)(nil),                   // 7: order.OrderDetail
	(*GetOrderByIdRequest)(nil),           // 8: order.GetOrderByIdRequest
	(*GetOrderByIdResponse)(nil),          // 9: order.GetOrderByIdResponse
	(*CreateOrderRequest)(nil),            // 10: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),           // 11: order.CreateOrderResponse
	(*AddOrderRequest)(nil),               // 12: order.AddOrderRequest
	(*AddOrderResponse)(nil),              // 13: order.AddOrderResponse
	(*CreateOrderDTMConfirmRequest)(nil),  // 14: order.CreateOrderDTMConfirmRequest
	(*CreateOrderDTMConfirmResponse)(nil), // 15: order.CreateOrderDTMConfirmResponse
	(*CreateOrderDTMRevertRequest)(nil),   // 16: order.CreateOrderDTMRevertRequest
	(*CreateOrderDTMRevertResponse)(nil),  // 17: order.CreateOrderDTMRevertResponse
}
var file_apps_order_rpc_order_proto_depIdxs = []int32{
	0,  // 0: order.OrdersRequest.status:type_name -> order.OrderStatus
	0,  // 1: order.OrderBase.status:type_name -> order.OrderStatus
	5,  // 2: order.OrderDetail.base:type_name -> order.OrderBase
	4,  // 3: order.OrderDetail.products:type_name -> order.OrderProductItem
	6,  // 4: order.OrderDetail.receiver:type_name -> order.ReceiverInfo
	1,  // 5: order.OrderDetail.payment_type:type_name -> order.PaymentType
	7,  // 6: order.GetOrderByIdResponse.order:type_name -> order.OrderDetail
	4,  // 7: order.CreateOrderRequest.items:type_name -> order.OrderProductItem
	4,  // 8: order.AddOrderRequest.items:type_name -> order.OrderProductItem
	2,  // 9: order.OrderService.Orders:input_type -> order.OrdersRequest
	8,  // 10: order.OrderService.GetOrderById:input_type -> order.GetOrderByIdRequest
	10, // 11: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	10, // 12: order.OrderService.CreateOrderCheck:input_type -> order.CreateOrderRequest
	10, // 13: order.OrderService.RollbackOrder:input_type -> order.CreateOrderRequest
	12, // 14: order.OrderService.CreateOrderDTM:input_type -> order.AddOrderRequest
	14, // 15: order.OrderService.CreateOrderDTMConfirm:input_type -> order.CreateOrderDTMConfirmRequest
	12, // 16: order.OrderService.CreateOrderDTMRevert:input_type -> order.AddOrderRequest
	3,  // 17: order.OrderService.Orders:output_type -> order.OrdersResponse
	9,  // 18: order.OrderService.GetOrderById:output_type -> order.GetOrderByIdResponse
	11, // 19: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	11, // 20: order.OrderService.CreateOrderCheck:output_type -> order.CreateOrderResponse
	11, // 21: order.OrderService.RollbackOrder:output_type -> order.CreateOrderResponse
	13, // 22: order.OrderService.CreateOrderDTM:output_type -> order.AddOrderResponse
	15, // 23: order.OrderService.CreateOrderDTMConfirm:output_type -> order.CreateOrderDTMConfirmResponse
	13, // 24: order.OrderService.CreateOrderDTMRevert:output_type -> order.AddOrderResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_apps_order_rpc_order_proto_init() }
func file_apps_order_rpc_order_proto_init() {
	if File_apps_order_rpc_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_order_rpc_order_proto_rawDesc), len(file_apps_order_rpc_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_order_rpc_order_proto_goTypes,
		DependencyIndexes: file_apps_order_rpc_order_proto_depIdxs,
		EnumInfos:         file_apps_order_rpc_order_proto_enumTypes,
		MessageInfos:      file_apps_order_rpc_order_proto_msgTypes,
	}.Build()
	File_apps_order_rpc_order_proto = out.File
	file_apps_order_rpc_order_proto_goTypes = nil
	file_apps_order_rpc_order_proto_depIdxs = nil
}
