// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cartFieldNames          = builder.RawFieldNames(&Cart{})
	cartRows                = strings.Join(cartFieldNames, ",")
	cartRowsExpectAutoSet   = strings.Join(stringx.Remove(cartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cartRowsWithPlaceHolder = strings.Join(stringx.Remove(cartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCartIdPrefix                          = "cache:cart:id:"
	cacheCartUserIdProductIdDeleteStatusPrefix = "cache:cart:userId:productId:deleteStatus:"
)

type (
	cartModel interface {
		Insert(ctx context.Context, data *Cart) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Cart, error)
		FindOneByUserIdProductIdDeleteStatus(ctx context.Context, userId int64, productId int64, deleteStatus int64) (*Cart, error)
		Update(ctx context.Context, data *Cart) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCartModel struct {
		sqlc.CachedConn
		table string
	}

	Cart struct {
		Id           int64     `db:"id"`            // 购物车ID
		UserId       int64     `db:"user_id"`       // 用户ID
		ProductId    int64     `db:"product_id"`    // 商品ID
		Price        int64     `db:"price"`         // 加入时商品售价
		Quantity     int64     `db:"quantity"`      // 商品数量
		Selected     int64     `db:"selected"`      // 是否选中（0=否，1=是）
		DeleteStatus int64     `db:"delete_status"` // 删除状态（0=正常，1=删除）
		CreateTime   time.Time `db:"create_time"`   // 创建时间
		UpdateTime   time.Time `db:"update_time"`   // 更新时间
	}
)

func newCartModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCartModel {
	return &defaultCartModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`cart`",
	}
}

func (m *defaultCartModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	cartIdKey := fmt.Sprintf("%s%v", cacheCartIdPrefix, id)
	cartUserIdProductIdDeleteStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheCartUserIdProductIdDeleteStatusPrefix, data.UserId, data.ProductId, data.DeleteStatus)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, cartIdKey, cartUserIdProductIdDeleteStatusKey)
	return err
}

func (m *defaultCartModel) FindOne(ctx context.Context, id int64) (*Cart, error) {
	cartIdKey := fmt.Sprintf("%s%v", cacheCartIdPrefix, id)
	var resp Cart
	err := m.QueryRowCtx(ctx, &resp, cartIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartModel) FindOneByUserIdProductIdDeleteStatus(ctx context.Context, userId int64, productId int64, deleteStatus int64) (*Cart, error) {
	cartUserIdProductIdDeleteStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheCartUserIdProductIdDeleteStatusPrefix, userId, productId, deleteStatus)
	var resp Cart
	err := m.QueryRowIndexCtx(ctx, &resp, cartUserIdProductIdDeleteStatusKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `product_id` = ? and `delete_status` = ? limit 1", cartRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, productId, deleteStatus); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartModel) Insert(ctx context.Context, data *Cart) (sql.Result, error) {
	cartIdKey := fmt.Sprintf("%s%v", cacheCartIdPrefix, data.Id)
	cartUserIdProductIdDeleteStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheCartUserIdProductIdDeleteStatusPrefix, data.UserId, data.ProductId, data.DeleteStatus)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, cartRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ProductId, data.Price, data.Quantity, data.Selected, data.DeleteStatus)
	}, cartIdKey, cartUserIdProductIdDeleteStatusKey)
	return ret, err
}

func (m *defaultCartModel) Update(ctx context.Context, newData *Cart) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	cartIdKey := fmt.Sprintf("%s%v", cacheCartIdPrefix, data.Id)
	cartUserIdProductIdDeleteStatusKey := fmt.Sprintf("%s%v:%v:%v", cacheCartUserIdProductIdDeleteStatusPrefix, data.UserId, data.ProductId, data.DeleteStatus)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cartRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ProductId, newData.Price, newData.Quantity, newData.Selected, newData.DeleteStatus, newData.Id)
	}, cartIdKey, cartUserIdProductIdDeleteStatusKey)
	return err
}

func (m *defaultCartModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCartIdPrefix, primary)
}

func (m *defaultCartModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCartModel) tableName() string {
	return m.table
}
