// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ===== 基本信息 =====
	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                            // 商品ID (SPU)
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         // 商品名称
	Brief    string `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief,omitempty"`                       // 简介
	Keywords string `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`                 // 关键词，用于搜索
	ImageUrl string `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // 主图URL
	// ===== 分类与品牌 =====
	CategoryId   int64  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`      // 主分类ID
	CategoryName string `protobuf:"bytes,7,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"` // 主分类名称
	CategoryIds  string `protobuf:"bytes,8,opt,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`    // 所有分类ID集合（逗号分隔）
	BrandId      int64  `protobuf:"varint,9,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`               // 品牌ID
	BrandName    string `protobuf:"bytes,10,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`         // 品牌名称
	// ===== 价格与库存 =====
	Price    float64 `protobuf:"fixed64,11,opt,name=price,proto3" json:"price,omitempty"`                      // 售价
	Stock    int64   `protobuf:"varint,12,opt,name=stock,proto3" json:"stock,omitempty"`                       // 当前库存
	LowStock int32   `protobuf:"varint,13,opt,name=low_stock,json=lowStock,proto3" json:"low_stock,omitempty"` // 库存预警值
	Sales    int32   `protobuf:"varint,14,opt,name=sales,proto3" json:"sales,omitempty"`                       // 销量
	// ===== 物理属性 =====
	Unit   string  `protobuf:"bytes,15,opt,name=unit,proto3" json:"unit,omitempty"`       // 单位（件 / 台 / 箱）
	Weight float32 `protobuf:"fixed32,16,opt,name=weight,proto3" json:"weight,omitempty"` // 重量(kg)
	// ===== 内容描述 =====
	DetailTitle string `protobuf:"bytes,17,opt,name=detail_title,json=detailTitle,proto3" json:"detail_title,omitempty"` // 详情标题
	DetailDesc  string `protobuf:"bytes,18,opt,name=detail_desc,json=detailDesc,proto3" json:"detail_desc,omitempty"`    // 详情描述
	DetailHtml  string `protobuf:"bytes,19,opt,name=detail_html,json=detailHtml,proto3" json:"detail_html,omitempty"`    // 富文本详情内容（HTML）
	// ===== 状态与控制 =====
	Sort                int32 `protobuf:"varint,20,opt,name=sort,proto3" json:"sort,omitempty"`                                                            // 排序值
	NewStatusSort       int32 `protobuf:"varint,21,opt,name=new_status_sort,json=newStatusSort,proto3" json:"new_status_sort,omitempty"`                   // 新品排序
	RecommendStatusSort int32 `protobuf:"varint,22,opt,name=recommend_status_sort,json=recommendStatusSort,proto3" json:"recommend_status_sort,omitempty"` // 推荐排序
	Status              int64 `protobuf:"varint,23,opt,name=status,proto3" json:"status,omitempty"`                                                        // 商品状态：0-下架，1-上架
	CreateTime          int64 `protobuf:"varint,24,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                              // 创建时间（时间戳）
	UpdateTime          int64 `protobuf:"varint,25,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`                              // 更新时间（时间戳）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProductData) Reset() {
	*x = ProductData{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductData) ProtoMessage() {}

func (x *ProductData) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductData.ProtoReflect.Descriptor instead.
func (*ProductData) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *ProductData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductData) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *ProductData) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *ProductData) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProductData) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductData) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ProductData) GetCategoryIds() string {
	if x != nil {
		return x.CategoryIds
	}
	return ""
}

func (x *ProductData) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *ProductData) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *ProductData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductData) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductData) GetLowStock() int32 {
	if x != nil {
		return x.LowStock
	}
	return 0
}

func (x *ProductData) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *ProductData) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ProductData) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductData) GetDetailTitle() string {
	if x != nil {
		return x.DetailTitle
	}
	return ""
}

func (x *ProductData) GetDetailDesc() string {
	if x != nil {
		return x.DetailDesc
	}
	return ""
}

func (x *ProductData) GetDetailHtml() string {
	if x != nil {
		return x.DetailHtml
	}
	return ""
}

func (x *ProductData) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProductData) GetNewStatusSort() int32 {
	if x != nil {
		return x.NewStatusSort
	}
	return 0
}

func (x *ProductData) GetRecommendStatusSort() int32 {
	if x != nil {
		return x.RecommendStatusSort
	}
	return 0
}

func (x *ProductData) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProductData) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ProductData) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

type CreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResp) Reset() {
	*x = CreateResp{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResp) ProtoMessage() {}

func (x *CreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
func (*CreateResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

type SearchSimpleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    //关键字
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    //页码
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` //每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimpleReq) Reset() {
	*x = SearchSimpleReq{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimpleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimpleReq) ProtoMessage() {}

func (x *SearchSimpleReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimpleReq.ProtoReflect.Descriptor instead.
func (*SearchSimpleReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSimpleReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchSimpleReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchSimpleReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Keyword  string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                    //关键字
	PageNum  int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    //页码
	PageSize int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` //每页数量
	Sort     int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`                         //排序字段:0->按相关度；1->按新品；2->按销量；3->价格从低到高；4->价格从高到低
	// ===== 过滤条件 =====
	CategoryIds []int64 `protobuf:"varint,5,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"` //分类ID列表（多选）
	BrandIds    []int64 `protobuf:"varint,6,rep,packed,name=brand_ids,json=brandIds,proto3" json:"brand_ids,omitempty"`          //品牌ID列表（多选）
	PriceMin    float64 `protobuf:"fixed64,7,opt,name=price_min,json=priceMin,proto3" json:"price_min,omitempty"`                //最低价格
	PriceMax    float64 `protobuf:"fixed64,8,opt,name=price_max,json=priceMax,proto3" json:"price_max,omitempty"`                //最高价格
	HasStock    bool    `protobuf:"varint,9,opt,name=has_stock,json=hasStock,proto3" json:"has_stock,omitempty"`                 //是否有库存
	Status      int64   `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                    //商品状态（1-上架，0-下架，默认1）
	// ===== 聚合查询 =====
	NeedAgg       bool `protobuf:"varint,11,opt,name=need_agg,json=needAgg,proto3" json:"need_agg,omitempty"` //是否需要聚合数据（默认false，减少不必要计算）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{6}
}

func (x *SearchReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SearchReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SearchReq) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *SearchReq) GetBrandIds() []int64 {
	if x != nil {
		return x.BrandIds
	}
	return nil
}

func (x *SearchReq) GetPriceMin() float64 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *SearchReq) GetPriceMax() float64 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *SearchReq) GetHasStock() bool {
	if x != nil {
		return x.HasStock
	}
	return false
}

func (x *SearchReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SearchReq) GetNeedAgg() bool {
	if x != nil {
		return x.NeedAgg
	}
	return false
}

type SearchResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []*ProductData         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`    //商品列表
	Total int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` //总数
	// ===== 聚合数据 =====
	BrandAggs      []*BrandAgg      `protobuf:"bytes,3,rep,name=brand_aggs,json=brandAggs,proto3" json:"brand_aggs,omitempty"`                  //品牌聚合
	CategoryAggs   []*CategoryAgg   `protobuf:"bytes,4,rep,name=category_aggs,json=categoryAggs,proto3" json:"category_aggs,omitempty"`         //分类聚合
	PriceRangeAggs []*PriceRangeAgg `protobuf:"bytes,5,rep,name=price_range_aggs,json=priceRangeAggs,proto3" json:"price_range_aggs,omitempty"` //价格区间聚合
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResp) GetData() []*ProductData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResp) GetBrandAggs() []*BrandAgg {
	if x != nil {
		return x.BrandAggs
	}
	return nil
}

func (x *SearchResp) GetCategoryAggs() []*CategoryAgg {
	if x != nil {
		return x.CategoryAggs
	}
	return nil
}

func (x *SearchResp) GetPriceRangeAggs() []*PriceRangeAgg {
	if x != nil {
		return x.PriceRangeAggs
	}
	return nil
}

// 品牌聚合
type BrandAgg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       int64                  `protobuf:"varint,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BrandName     string                 `protobuf:"bytes,2,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` //该品牌下的商品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandAgg) Reset() {
	*x = BrandAgg{}
	mi := &file_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandAgg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandAgg) ProtoMessage() {}

func (x *BrandAgg) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandAgg.ProtoReflect.Descriptor instead.
func (*BrandAgg) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{8}
}

func (x *BrandAgg) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *BrandAgg) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *BrandAgg) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 分类聚合
type CategoryAgg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` //该分类下的商品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryAgg) Reset() {
	*x = CategoryAgg{}
	mi := &file_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryAgg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryAgg) ProtoMessage() {}

func (x *CategoryAgg) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryAgg.ProtoReflect.Descriptor instead.
func (*CategoryAgg) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryAgg) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryAgg) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryAgg) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 价格区间聚合
type PriceRangeAgg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeKey      string                 `protobuf:"bytes,1,opt,name=range_key,json=rangeKey,proto3" json:"range_key,omitempty"`       //区间标识，如 "0-100", "100-500", "500+"
	RangeLabel    string                 `protobuf:"bytes,2,opt,name=range_label,json=rangeLabel,proto3" json:"range_label,omitempty"` //区间显示标签，如 "0-100元", "100-500元", "500元以上"
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                            //该区间内的商品数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRangeAgg) Reset() {
	*x = PriceRangeAgg{}
	mi := &file_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRangeAgg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRangeAgg) ProtoMessage() {}

func (x *PriceRangeAgg) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRangeAgg.ProtoReflect.Descriptor instead.
func (*PriceRangeAgg) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{10}
}

func (x *PriceRangeAgg) GetRangeKey() string {
	if x != nil {
		return x.RangeKey
	}
	return ""
}

func (x *PriceRangeAgg) GetRangeLabel() string {
	if x != nil {
		return x.RangeLabel
	}
	return ""
}

func (x *PriceRangeAgg) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecommendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`                          //关键字
	PageNum       int64                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`          //页码
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       //每页数量
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`                                //排序
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"` //商品分类ID
	BrandId       int64                  `protobuf:"varint,6,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`          //品牌ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendReq) Reset() {
	*x = RecommendReq{}
	mi := &file_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendReq) ProtoMessage() {}

func (x *RecommendReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendReq.ProtoReflect.Descriptor instead.
func (*RecommendReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{11}
}

func (x *RecommendReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *RecommendReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *RecommendReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RecommendReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *RecommendReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *RecommendReq) GetBrandId() int64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

type RecommendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductData         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` //商品列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResp) Reset() {
	*x = RecommendResp{}
	mi := &file_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResp) ProtoMessage() {}

func (x *RecommendResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResp.ProtoReflect.Descriptor instead.
func (*RecommendResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{12}
}

func (x *RecommendResp) GetData() []*ProductData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchRelatedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"` //关键字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRelatedReq) Reset() {
	*x = SearchRelatedReq{}
	mi := &file_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRelatedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRelatedReq) ProtoMessage() {}

func (x *SearchRelatedReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRelatedReq.ProtoReflect.Descriptor instead.
func (*SearchRelatedReq) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{13}
}

func (x *SearchRelatedReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchRelatedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandNames    []string               `protobuf:"bytes,1,rep,name=brand_names,json=brandNames,proto3" json:"brand_names,omitempty"`          //品牌名称集合
	CategoryNames []string               `protobuf:"bytes,2,rep,name=category_names,json=categoryNames,proto3" json:"category_names,omitempty"` //分类名称集合
	ProductAttrs  []*ProductAttr         `protobuf:"bytes,3,rep,name=productAttrs,proto3" json:"productAttrs,omitempty"`                        //属性集合
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRelatedResp) Reset() {
	*x = SearchRelatedResp{}
	mi := &file_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRelatedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRelatedResp) ProtoMessage() {}

func (x *SearchRelatedResp) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRelatedResp.ProtoReflect.Descriptor instead.
func (*SearchRelatedResp) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{14}
}

func (x *SearchRelatedResp) GetBrandNames() []string {
	if x != nil {
		return x.BrandNames
	}
	return nil
}

func (x *SearchRelatedResp) GetCategoryNames() []string {
	if x != nil {
		return x.CategoryNames
	}
	return nil
}

func (x *SearchRelatedResp) GetProductAttrs() []*ProductAttr {
	if x != nil {
		return x.ProductAttrs
	}
	return nil
}

type ProductAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrId        int64                  `protobuf:"varint,1,opt,name=attrId,proto3" json:"attrId,omitempty"`        //属性id
	AttrName      string                 `protobuf:"bytes,2,opt,name=attrName,proto3" json:"attrName,omitempty"`     //属性名称
	AttrValues    []string               `protobuf:"bytes,3,rep,name=attrValues,proto3" json:"attrValues,omitempty"` //属性值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAttr) Reset() {
	*x = ProductAttr{}
	mi := &file_search_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAttr) ProtoMessage() {}

func (x *ProductAttr) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAttr.ProtoReflect.Descriptor instead.
func (*ProductAttr) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{15}
}

func (x *ProductAttr) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *ProductAttr) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *ProductAttr) GetAttrValues() []string {
	if x != nil {
		return x.AttrValues
	}
	return nil
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x06search\"\xdd\x05\n" +
	"\vProductData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brief\x18\x03 \x01(\tR\x05brief\x12\x1a\n" +
	"\bkeywords\x18\x04 \x01(\tR\bkeywords\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\a \x01(\tR\fcategoryName\x12!\n" +
	"\fcategory_ids\x18\b \x01(\tR\vcategoryIds\x12\x19\n" +
	"\bbrand_id\x18\t \x01(\x03R\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\n" +
	" \x01(\tR\tbrandName\x12\x14\n" +
	"\x05price\x18\v \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\f \x01(\x03R\x05stock\x12\x1b\n" +
	"\tlow_stock\x18\r \x01(\x05R\blowStock\x12\x14\n" +
	"\x05sales\x18\x0e \x01(\x05R\x05sales\x12\x12\n" +
	"\x04unit\x18\x0f \x01(\tR\x04unit\x12\x16\n" +
	"\x06weight\x18\x10 \x01(\x02R\x06weight\x12!\n" +
	"\fdetail_title\x18\x11 \x01(\tR\vdetailTitle\x12\x1f\n" +
	"\vdetail_desc\x18\x12 \x01(\tR\n" +
	"detailDesc\x12\x1f\n" +
	"\vdetail_html\x18\x13 \x01(\tR\n" +
	"detailHtml\x12\x12\n" +
	"\x04sort\x18\x14 \x01(\x05R\x04sort\x12&\n" +
	"\x0fnew_status_sort\x18\x15 \x01(\x05R\rnewStatusSort\x122\n" +
	"\x15recommend_status_sort\x18\x16 \x01(\x05R\x13recommendStatusSort\x12\x16\n" +
	"\x06status\x18\x17 \x01(\x03R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\x18 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x19 \x01(\x03R\n" +
	"updateTime\"\v\n" +
	"\tCreateReq\"\f\n" +
	"\n" +
	"CreateResp\"\x1d\n" +
	"\tDeleteReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\f\n" +
	"\n" +
	"DeleteResp\"c\n" +
	"\x0fSearchSimpleReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"\xbb\x02\n" +
	"\tSearchReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12!\n" +
	"\fcategory_ids\x18\x05 \x03(\x03R\vcategoryIds\x12\x1b\n" +
	"\tbrand_ids\x18\x06 \x03(\x03R\bbrandIds\x12\x1b\n" +
	"\tprice_min\x18\a \x01(\x01R\bpriceMin\x12\x1b\n" +
	"\tprice_max\x18\b \x01(\x01R\bpriceMax\x12\x1b\n" +
	"\thas_stock\x18\t \x01(\bR\bhasStock\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x03R\x06status\x12\x19\n" +
	"\bneed_agg\x18\v \x01(\bR\aneedAgg\"\xf7\x01\n" +
	"\n" +
	"SearchResp\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.search.ProductDataR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12/\n" +
	"\n" +
	"brand_aggs\x18\x03 \x03(\v2\x10.search.BrandAggR\tbrandAggs\x128\n" +
	"\rcategory_aggs\x18\x04 \x03(\v2\x13.search.CategoryAggR\fcategoryAggs\x12?\n" +
	"\x10price_range_aggs\x18\x05 \x03(\v2\x15.search.PriceRangeAggR\x0epriceRangeAggs\"Z\n" +
	"\bBrandAgg\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\x03R\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x02 \x01(\tR\tbrandName\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"i\n" +
	"\vCategoryAgg\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"c\n" +
	"\rPriceRangeAgg\x12\x1b\n" +
	"\trange_key\x18\x01 \x01(\tR\brangeKey\x12\x1f\n" +
	"\vrange_label\x18\x02 \x01(\tR\n" +
	"rangeLabel\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"\xb0\x01\n" +
	"\fRecommendReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x03R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x06 \x01(\x03R\abrandId\"8\n" +
	"\rRecommendResp\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.search.ProductDataR\x04data\",\n" +
	"\x10SearchRelatedReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"\x94\x01\n" +
	"\x11SearchRelatedResp\x12\x1f\n" +
	"\vbrand_names\x18\x01 \x03(\tR\n" +
	"brandNames\x12%\n" +
	"\x0ecategory_names\x18\x02 \x03(\tR\rcategoryNames\x127\n" +
	"\fproductAttrs\x18\x03 \x03(\v2\x13.search.ProductAttrR\fproductAttrs\"a\n" +
	"\vProductAttr\x12\x16\n" +
	"\x06attrId\x18\x01 \x01(\x03R\x06attrId\x12\x1a\n" +
	"\battrName\x18\x02 \x01(\tR\battrName\x12\x1e\n" +
	"\n" +
	"attrValues\x18\x03 \x03(\tR\n" +
	"attrValues2\xd5\x02\n" +
	"\x06Search\x12/\n" +
	"\x06create\x12\x11.search.CreateReq\x1a\x12.search.CreateResp\x12/\n" +
	"\x06delete\x12\x11.search.DeleteReq\x1a\x12.search.DeleteResp\x12;\n" +
	"\fsearchSimple\x12\x17.search.SearchSimpleReq\x1a\x12.search.SearchResp\x12/\n" +
	"\x06search\x12\x11.search.SearchReq\x1a\x12.search.SearchResp\x125\n" +
	"\trecommend\x12\x14.search.RecommendReq\x1a\x12.search.SearchResp\x12D\n" +
	"\rsearchRelated\x12\x18.search.SearchRelatedReq\x1a\x19.search.SearchRelatedRespB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_search_proto_goTypes = []any{
	(*ProductData)(nil),       // 0: search.ProductData
	(*CreateReq)(nil),         // 1: search.CreateReq
	(*CreateResp)(nil),        // 2: search.CreateResp
	(*DeleteReq)(nil),         // 3: search.DeleteReq
	(*DeleteResp)(nil),        // 4: search.DeleteResp
	(*SearchSimpleReq)(nil),   // 5: search.SearchSimpleReq
	(*SearchReq)(nil),         // 6: search.SearchReq
	(*SearchResp)(nil),        // 7: search.SearchResp
	(*BrandAgg)(nil),          // 8: search.BrandAgg
	(*CategoryAgg)(nil),       // 9: search.CategoryAgg
	(*PriceRangeAgg)(nil),     // 10: search.PriceRangeAgg
	(*RecommendReq)(nil),      // 11: search.RecommendReq
	(*RecommendResp)(nil),     // 12: search.RecommendResp
	(*SearchRelatedReq)(nil),  // 13: search.SearchRelatedReq
	(*SearchRelatedResp)(nil), // 14: search.SearchRelatedResp
	(*ProductAttr)(nil),       // 15: search.ProductAttr
}
var file_search_proto_depIdxs = []int32{
	0,  // 0: search.SearchResp.data:type_name -> search.ProductData
	8,  // 1: search.SearchResp.brand_aggs:type_name -> search.BrandAgg
	9,  // 2: search.SearchResp.category_aggs:type_name -> search.CategoryAgg
	10, // 3: search.SearchResp.price_range_aggs:type_name -> search.PriceRangeAgg
	0,  // 4: search.RecommendResp.data:type_name -> search.ProductData
	15, // 5: search.SearchRelatedResp.productAttrs:type_name -> search.ProductAttr
	1,  // 6: search.Search.create:input_type -> search.CreateReq
	3,  // 7: search.Search.delete:input_type -> search.DeleteReq
	5,  // 8: search.Search.searchSimple:input_type -> search.SearchSimpleReq
	6,  // 9: search.Search.search:input_type -> search.SearchReq
	11, // 10: search.Search.recommend:input_type -> search.RecommendReq
	13, // 11: search.Search.searchRelated:input_type -> search.SearchRelatedReq
	2,  // 12: search.Search.create:output_type -> search.CreateResp
	4,  // 13: search.Search.delete:output_type -> search.DeleteResp
	7,  // 14: search.Search.searchSimple:output_type -> search.SearchResp
	7,  // 15: search.Search.search:output_type -> search.SearchResp
	7,  // 16: search.Search.recommend:output_type -> search.SearchResp
	14, // 17: search.Search.searchRelated:output_type -> search.SearchRelatedResp
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
