apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
  namespace: go-zero-shop
  labels:
    app: go-zero-shop
data:
  TZ: "Asia/Shanghai"
  LOG_LEVEL: "info"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  ETCD_HOSTS: "etcd:2379"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  ELASTICSEARCH_HOST: "http://elasticsearch:9200"
  DTM_GRPC_ADDR: "dtm:36790"
  JAEGER_COLLECTOR_ENDPOINT: "http://jaeger:14268/api/traces"
