// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"` //MD5加密
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Question      string                 `protobuf:"bytes,5,opt,name=Question,proto3" json:"Question,omitempty"` //找回密码问题
	Answer        string                 `protobuf:"bytes,6,opt,name=Answer,proto3" json:"Answer,omitempty"`     //找回密码答案
	CreateTime    int64                  `protobuf:"varint,7,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,8,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	IntroduceSign string                 `protobuf:"bytes,9,opt,name=IntroduceSign,proto3" json:"IntroduceSign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *UserInfo) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *UserInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UserInfo) GetIntroduceSign() string {
	if x != nil {
		return x.IntroduceSign
	}
	return ""
}

// 用户登录
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 用户信息
type UserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

// 添加用户收货地址
type UserReceiveAddressAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	IsDefault     int32                  `protobuf:"varint,4,opt,name=IsDefault,proto3" json:"IsDefault,omitempty"` //是否为默认地址。
	Province      string                 `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`    //省份/直辖市
	City          string                 `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=Region,proto3" json:"Region,omitempty"` //区
	DetailAddress string                 `protobuf:"bytes,8,opt,name=DetailAddress,proto3" json:"DetailAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressAddRequest) Reset() {
	*x = UserReceiveAddressAddRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressAddRequest) ProtoMessage() {}

func (x *UserReceiveAddressAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressAddRequest.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressAddRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserReceiveAddressAddRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserReceiveAddressAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReceiveAddressAddRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserReceiveAddressAddRequest) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *UserReceiveAddressAddRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserReceiveAddressAddRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserReceiveAddressAddRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UserReceiveAddressAddRequest) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

type UserReceiveAddressAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressAddResponse) Reset() {
	*x = UserReceiveAddressAddResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressAddResponse) ProtoMessage() {}

func (x *UserReceiveAddressAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressAddResponse.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressAddResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

// 获取收货地址列表
type UserReceiveAddressListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressListRequest) Reset() {
	*x = UserReceiveAddressListRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressListRequest) ProtoMessage() {}

func (x *UserReceiveAddressListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressListRequest.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserReceiveAddressListRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserReceiveAddressListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserReceiveAddress  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressListResponse) Reset() {
	*x = UserReceiveAddressListResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressListResponse) ProtoMessage() {}

func (x *UserReceiveAddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressListResponse.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserReceiveAddressListResponse) GetList() []*UserReceiveAddress {
	if x != nil {
		return x.List
	}
	return nil
}

type UserReceiveAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                    //uid
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                   //收货人名称
	Phone         string                 `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`                 //手机号
	IsDefault     int32                  `protobuf:"varint,5,opt,name=IsDefault,proto3" json:"IsDefault,omitempty"`        //是否为默认地址
	Province      string                 `protobuf:"bytes,6,opt,name=Province,proto3" json:"Province,omitempty"`           //省份/直辖市
	City          string                 `protobuf:"bytes,7,opt,name=City,proto3" json:"City,omitempty"`                   //城市
	Region        string                 `protobuf:"bytes,8,opt,name=Region,proto3" json:"Region,omitempty"`               //区
	DetailAddress string                 `protobuf:"bytes,9,opt,name=DetailAddress,proto3" json:"DetailAddress,omitempty"` //详细地址(街道)
	IsDelete      int32                  `protobuf:"varint,10,opt,name=IsDelete,proto3" json:"IsDelete,omitempty"`
	CreateTime    int64                  `protobuf:"varint,11,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,12,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddress) Reset() {
	*x = UserReceiveAddress{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddress) ProtoMessage() {}

func (x *UserReceiveAddress) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddress.ProtoReflect.Descriptor instead.
func (*UserReceiveAddress) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserReceiveAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReceiveAddress) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserReceiveAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReceiveAddress) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserReceiveAddress) GetIsDefault() int32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *UserReceiveAddress) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserReceiveAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserReceiveAddress) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UserReceiveAddress) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

func (x *UserReceiveAddress) GetIsDelete() int32 {
	if x != nil {
		return x.IsDelete
	}
	return 0
}

func (x *UserReceiveAddress) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UserReceiveAddress) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 更新
type UserReceiveAddressEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                   //收货人名称
	Phone         string                 `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`                 //手机号
	IsDefault     uint32                 `protobuf:"varint,4,opt,name=IsDefault,proto3" json:"IsDefault,omitempty"`        //是否为默认地址
	Province      string                 `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`           //省份/直辖市
	City          string                 `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`                   //城市
	Region        string                 `protobuf:"bytes,7,opt,name=Region,proto3" json:"Region,omitempty"`               //区
	DetailAddress string                 `protobuf:"bytes,8,opt,name=DetailAddress,proto3" json:"DetailAddress,omitempty"` //详细地址(街道)
	Uid           int64                  `protobuf:"varint,9,opt,name=Uid,proto3" json:"Uid,omitempty"`                    //用户 Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressEditRequest) Reset() {
	*x = UserReceiveAddressEditRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressEditRequest) ProtoMessage() {}

func (x *UserReceiveAddressEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressEditRequest.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressEditRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserReceiveAddressEditRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReceiveAddressEditRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReceiveAddressEditRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserReceiveAddressEditRequest) GetIsDefault() uint32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *UserReceiveAddressEditRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserReceiveAddressEditRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserReceiveAddressEditRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *UserReceiveAddressEditRequest) GetDetailAddress() string {
	if x != nil {
		return x.DetailAddress
	}
	return ""
}

func (x *UserReceiveAddressEditRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserReceiveAddressEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressEditResponse) Reset() {
	*x = UserReceiveAddressEditResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressEditResponse) ProtoMessage() {}

func (x *UserReceiveAddressEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressEditResponse.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressEditResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

type UserReceiveAddressDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressDelRequest) Reset() {
	*x = UserReceiveAddressDelRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressDelRequest) ProtoMessage() {}

func (x *UserReceiveAddressDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressDelRequest.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressDelRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserReceiveAddressDelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserReceiveAddressDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressDelResponse) Reset() {
	*x = UserReceiveAddressDelResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressDelResponse) ProtoMessage() {}

func (x *UserReceiveAddressDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressDelResponse.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressDelResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

// 添加收藏
type UserCollectionAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCollectionAddRequest) Reset() {
	*x = UserCollectionAddRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCollectionAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCollectionAddRequest) ProtoMessage() {}

func (x *UserCollectionAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCollectionAddRequest.ProtoReflect.Descriptor instead.
func (*UserCollectionAddRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserCollectionAddRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserCollectionAddRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type UserCollectionAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCollectionAddResponse) Reset() {
	*x = UserCollectionAddResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCollectionAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCollectionAddResponse) ProtoMessage() {}

func (x *UserCollectionAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCollectionAddResponse.ProtoReflect.Descriptor instead.
func (*UserCollectionAddResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

// 删除收藏
type UserCollectionDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // 收藏Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCollectionDelRequest) Reset() {
	*x = UserCollectionDelRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCollectionDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCollectionDelRequest) ProtoMessage() {}

func (x *UserCollectionDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCollectionDelRequest.ProtoReflect.Descriptor instead.
func (*UserCollectionDelRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UserCollectionDelRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserCollectionDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCollectionDelResponse) Reset() {
	*x = UserCollectionDelResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCollectionDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCollectionDelResponse) ProtoMessage() {}

func (x *UserCollectionDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCollectionDelResponse.ProtoReflect.Descriptor instead.
func (*UserCollectionDelResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

// 收藏列表
type UserCollectionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCollectionListRequest) Reset() {
	*x = UserCollectionListRequest{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCollectionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCollectionListRequest) ProtoMessage() {}

func (x *UserCollectionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCollectionListRequest.ProtoReflect.Descriptor instead.
func (*UserCollectionListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *UserCollectionListRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserCollectionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     []int64                `protobuf:"varint,1,rep,packed,name=ProductId,proto3" json:"ProductId,omitempty"` // 商品id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCollectionListResponse) Reset() {
	*x = UserCollectionListResponse{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCollectionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCollectionListResponse) ProtoMessage() {}

func (x *UserCollectionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCollectionListResponse.ProtoReflect.Descriptor instead.
func (*UserCollectionListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *UserCollectionListResponse) GetProductId() []int64 {
	if x != nil {
		return x.ProductId
	}
	return nil
}

type UserReceiveAddressInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReceiveAddressInfoRequest) Reset() {
	*x = UserReceiveAddressInfoRequest{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReceiveAddressInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReceiveAddressInfoRequest) ProtoMessage() {}

func (x *UserReceiveAddressInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReceiveAddressInfoRequest.ProtoReflect.Descriptor instead.
func (*UserReceiveAddressInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *UserReceiveAddressInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\x82\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bQuestion\x18\x05 \x01(\tR\bQuestion\x12\x16\n" +
	"\x06Answer\x18\x06 \x01(\tR\x06Answer\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\a \x01(\x03R\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\b \x01(\x03R\n" +
	"UpdateTime\x12$\n" +
	"\rIntroduceSign\x18\t \x01(\tR\rIntroduceSign\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"Q\n" +
	"\rLoginResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Phone\x18\x03 \x01(\tR\x05Phone\"!\n" +
	"\x0fUserInfoRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"6\n" +
	"\x10UserInfoResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"\xe6\x01\n" +
	"\x1cUserReceiveAddressAddRequest\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x03 \x01(\tR\x05Phone\x12\x1c\n" +
	"\tIsDefault\x18\x04 \x01(\x05R\tIsDefault\x12\x1a\n" +
	"\bProvince\x18\x05 \x01(\tR\bProvince\x12\x12\n" +
	"\x04City\x18\x06 \x01(\tR\x04City\x12\x16\n" +
	"\x06Region\x18\a \x01(\tR\x06Region\x12$\n" +
	"\rDetailAddress\x18\b \x01(\tR\rDetailAddress\"\x1f\n" +
	"\x1dUserReceiveAddressAddResponse\"1\n" +
	"\x1dUserReceiveAddressListRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"N\n" +
	"\x1eUserReceiveAddressListResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.user.UserReceiveAddressR\x04list\"\xc8\x02\n" +
	"\x12UserReceiveAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x04 \x01(\tR\x05Phone\x12\x1c\n" +
	"\tIsDefault\x18\x05 \x01(\x05R\tIsDefault\x12\x1a\n" +
	"\bProvince\x18\x06 \x01(\tR\bProvince\x12\x12\n" +
	"\x04City\x18\a \x01(\tR\x04City\x12\x16\n" +
	"\x06Region\x18\b \x01(\tR\x06Region\x12$\n" +
	"\rDetailAddress\x18\t \x01(\tR\rDetailAddress\x12\x1a\n" +
	"\bIsDelete\x18\n" +
	" \x01(\x05R\bIsDelete\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\v \x01(\x03R\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\f \x01(\x03R\n" +
	"UpdateTime\"\xf7\x01\n" +
	"\x1dUserReceiveAddressEditRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Phone\x18\x03 \x01(\tR\x05Phone\x12\x1c\n" +
	"\tIsDefault\x18\x04 \x01(\rR\tIsDefault\x12\x1a\n" +
	"\bProvince\x18\x05 \x01(\tR\bProvince\x12\x12\n" +
	"\x04City\x18\x06 \x01(\tR\x04City\x12\x16\n" +
	"\x06Region\x18\a \x01(\tR\x06Region\x12$\n" +
	"\rDetailAddress\x18\b \x01(\tR\rDetailAddress\x12\x10\n" +
	"\x03Uid\x18\t \x01(\x03R\x03Uid\" \n" +
	"\x1eUserReceiveAddressEditResponse\".\n" +
	"\x1cUserReceiveAddressDelRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"\x1f\n" +
	"\x1dUserReceiveAddressDelResponse\"J\n" +
	"\x18UserCollectionAddRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1c\n" +
	"\tProductId\x18\x02 \x01(\x03R\tProductId\"\x1b\n" +
	"\x19UserCollectionAddResponse\"*\n" +
	"\x18UserCollectionDelRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"\x1b\n" +
	"\x19UserCollectionDelResponse\"-\n" +
	"\x19UserCollectionListRequest\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x03R\x03Uid\":\n" +
	"\x1aUserCollectionListResponse\x12\x1c\n" +
	"\tProductId\x18\x01 \x03(\x03R\tProductId\"/\n" +
	"\x1dUserReceiveAddressInfoRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id2\xe8\x06\n" +
	"\x04User\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x129\n" +
	"\bUserInfo\x12\x15.user.UserInfoRequest\x1a\x16.user.UserInfoResponse\x12`\n" +
	"\x15addUserReceiveAddress\x12\".user.UserReceiveAddressAddRequest\x1a#.user.UserReceiveAddressAddResponse\x12c\n" +
	"\x16editUserReceiveAddress\x12#.user.UserReceiveAddressEditRequest\x1a$.user.UserReceiveAddressEditResponse\x12`\n" +
	"\x15delUserReceiveAddress\x12\".user.UserReceiveAddressDelRequest\x1a#.user.UserReceiveAddressDelResponse\x12f\n" +
	"\x19getUserReceiveAddressList\x12#.user.UserReceiveAddressListRequest\x1a$.user.UserReceiveAddressListResponse\x12T\n" +
	"\x11addUserCollection\x12\x1e.user.UserCollectionAddRequest\x1a\x1f.user.UserCollectionAddResponse\x12T\n" +
	"\x11delUserCollection\x12\x1e.user.UserCollectionDelRequest\x1a\x1f.user.UserCollectionDelResponse\x12Z\n" +
	"\x15getUserCollectionList\x12\x1f.user.UserCollectionListRequest\x1a .user.UserCollectionListResponse\x12Z\n" +
	"\x19getUserReceiveAddressInfo\x12#.user.UserReceiveAddressInfoRequest\x1a\x18.user.UserReceiveAddressB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_user_proto_goTypes = []any{
	(*UserInfo)(nil),                       // 0: user.UserInfo
	(*LoginRequest)(nil),                   // 1: user.LoginRequest
	(*LoginResponse)(nil),                  // 2: user.LoginResponse
	(*UserInfoRequest)(nil),                // 3: user.UserInfoRequest
	(*UserInfoResponse)(nil),               // 4: user.UserInfoResponse
	(*UserReceiveAddressAddRequest)(nil),   // 5: user.UserReceiveAddressAddRequest
	(*UserReceiveAddressAddResponse)(nil),  // 6: user.UserReceiveAddressAddResponse
	(*UserReceiveAddressListRequest)(nil),  // 7: user.UserReceiveAddressListRequest
	(*UserReceiveAddressListResponse)(nil), // 8: user.UserReceiveAddressListResponse
	(*UserReceiveAddress)(nil),             // 9: user.UserReceiveAddress
	(*UserReceiveAddressEditRequest)(nil),  // 10: user.UserReceiveAddressEditRequest
	(*UserReceiveAddressEditResponse)(nil), // 11: user.UserReceiveAddressEditResponse
	(*UserReceiveAddressDelRequest)(nil),   // 12: user.UserReceiveAddressDelRequest
	(*UserReceiveAddressDelResponse)(nil),  // 13: user.UserReceiveAddressDelResponse
	(*UserCollectionAddRequest)(nil),       // 14: user.UserCollectionAddRequest
	(*UserCollectionAddResponse)(nil),      // 15: user.UserCollectionAddResponse
	(*UserCollectionDelRequest)(nil),       // 16: user.UserCollectionDelRequest
	(*UserCollectionDelResponse)(nil),      // 17: user.UserCollectionDelResponse
	(*UserCollectionListRequest)(nil),      // 18: user.UserCollectionListRequest
	(*UserCollectionListResponse)(nil),     // 19: user.UserCollectionListResponse
	(*UserReceiveAddressInfoRequest)(nil),  // 20: user.UserReceiveAddressInfoRequest
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.UserInfoResponse.user:type_name -> user.UserInfo
	9,  // 1: user.UserReceiveAddressListResponse.list:type_name -> user.UserReceiveAddress
	1,  // 2: user.User.Login:input_type -> user.LoginRequest
	3,  // 3: user.User.UserInfo:input_type -> user.UserInfoRequest
	5,  // 4: user.User.addUserReceiveAddress:input_type -> user.UserReceiveAddressAddRequest
	10, // 5: user.User.editUserReceiveAddress:input_type -> user.UserReceiveAddressEditRequest
	12, // 6: user.User.delUserReceiveAddress:input_type -> user.UserReceiveAddressDelRequest
	7,  // 7: user.User.getUserReceiveAddressList:input_type -> user.UserReceiveAddressListRequest
	14, // 8: user.User.addUserCollection:input_type -> user.UserCollectionAddRequest
	16, // 9: user.User.delUserCollection:input_type -> user.UserCollectionDelRequest
	18, // 10: user.User.getUserCollectionList:input_type -> user.UserCollectionListRequest
	20, // 11: user.User.getUserReceiveAddressInfo:input_type -> user.UserReceiveAddressInfoRequest
	2,  // 12: user.User.Login:output_type -> user.LoginResponse
	4,  // 13: user.User.UserInfo:output_type -> user.UserInfoResponse
	6,  // 14: user.User.addUserReceiveAddress:output_type -> user.UserReceiveAddressAddResponse
	11, // 15: user.User.editUserReceiveAddress:output_type -> user.UserReceiveAddressEditResponse
	13, // 16: user.User.delUserReceiveAddress:output_type -> user.UserReceiveAddressDelResponse
	8,  // 17: user.User.getUserReceiveAddressList:output_type -> user.UserReceiveAddressListResponse
	15, // 18: user.User.addUserCollection:output_type -> user.UserCollectionAddResponse
	17, // 19: user.User.delUserCollection:output_type -> user.UserCollectionDelResponse
	19, // 20: user.User.getUserCollectionList:output_type -> user.UserCollectionListResponse
	9,  // 21: user.User.getUserReceiveAddressInfo:output_type -> user.UserReceiveAddress
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
