// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_Login_FullMethodName                     = "/user.User/Login"
	User_UserInfo_FullMethodName                  = "/user.User/UserInfo"
	User_AddUserReceiveAddress_FullMethodName     = "/user.User/addUserReceiveAddress"
	User_EditUserReceiveAddress_FullMethodName    = "/user.User/editUserReceiveAddress"
	User_DelUserReceiveAddress_FullMethodName     = "/user.User/delUserReceiveAddress"
	User_GetUserReceiveAddressList_FullMethodName = "/user.User/getUserReceiveAddressList"
	User_AddUserCollection_FullMethodName         = "/user.User/addUserCollection"
	User_DelUserCollection_FullMethodName         = "/user.User/delUserCollection"
	User_GetUserCollectionList_FullMethodName     = "/user.User/getUserCollectionList"
	User_GetUserReceiveAddressInfo_FullMethodName = "/user.User/getUserReceiveAddressInfo"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	// 登录
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// 获取用户信息
	UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	// 添加收获地址
	AddUserReceiveAddress(ctx context.Context, in *UserReceiveAddressAddRequest, opts ...grpc.CallOption) (*UserReceiveAddressAddResponse, error)
	// 编辑收获地址
	EditUserReceiveAddress(ctx context.Context, in *UserReceiveAddressEditRequest, opts ...grpc.CallOption) (*UserReceiveAddressEditResponse, error)
	// 删除收获地址
	DelUserReceiveAddress(ctx context.Context, in *UserReceiveAddressDelRequest, opts ...grpc.CallOption) (*UserReceiveAddressDelResponse, error)
	// 获取收获地址列表
	GetUserReceiveAddressList(ctx context.Context, in *UserReceiveAddressListRequest, opts ...grpc.CallOption) (*UserReceiveAddressListResponse, error)
	// 添加收藏
	AddUserCollection(ctx context.Context, in *UserCollectionAddRequest, opts ...grpc.CallOption) (*UserCollectionAddResponse, error)
	// 删除收藏
	DelUserCollection(ctx context.Context, in *UserCollectionDelRequest, opts ...grpc.CallOption) (*UserCollectionDelResponse, error)
	// 收藏列表
	GetUserCollectionList(ctx context.Context, in *UserCollectionListRequest, opts ...grpc.CallOption) (*UserCollectionListResponse, error)
	// 根据主键id,查询收获地址
	GetUserReceiveAddressInfo(ctx context.Context, in *UserReceiveAddressInfoRequest, opts ...grpc.CallOption) (*UserReceiveAddress, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, User_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, User_UserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddUserReceiveAddress(ctx context.Context, in *UserReceiveAddressAddRequest, opts ...grpc.CallOption) (*UserReceiveAddressAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReceiveAddressAddResponse)
	err := c.cc.Invoke(ctx, User_AddUserReceiveAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) EditUserReceiveAddress(ctx context.Context, in *UserReceiveAddressEditRequest, opts ...grpc.CallOption) (*UserReceiveAddressEditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReceiveAddressEditResponse)
	err := c.cc.Invoke(ctx, User_EditUserReceiveAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DelUserReceiveAddress(ctx context.Context, in *UserReceiveAddressDelRequest, opts ...grpc.CallOption) (*UserReceiveAddressDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReceiveAddressDelResponse)
	err := c.cc.Invoke(ctx, User_DelUserReceiveAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserReceiveAddressList(ctx context.Context, in *UserReceiveAddressListRequest, opts ...grpc.CallOption) (*UserReceiveAddressListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReceiveAddressListResponse)
	err := c.cc.Invoke(ctx, User_GetUserReceiveAddressList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddUserCollection(ctx context.Context, in *UserCollectionAddRequest, opts ...grpc.CallOption) (*UserCollectionAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCollectionAddResponse)
	err := c.cc.Invoke(ctx, User_AddUserCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DelUserCollection(ctx context.Context, in *UserCollectionDelRequest, opts ...grpc.CallOption) (*UserCollectionDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCollectionDelResponse)
	err := c.cc.Invoke(ctx, User_DelUserCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserCollectionList(ctx context.Context, in *UserCollectionListRequest, opts ...grpc.CallOption) (*UserCollectionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCollectionListResponse)
	err := c.cc.Invoke(ctx, User_GetUserCollectionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserReceiveAddressInfo(ctx context.Context, in *UserReceiveAddressInfoRequest, opts ...grpc.CallOption) (*UserReceiveAddress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserReceiveAddress)
	err := c.cc.Invoke(ctx, User_GetUserReceiveAddressInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	// 登录
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// 获取用户信息
	UserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error)
	// 添加收获地址
	AddUserReceiveAddress(context.Context, *UserReceiveAddressAddRequest) (*UserReceiveAddressAddResponse, error)
	// 编辑收获地址
	EditUserReceiveAddress(context.Context, *UserReceiveAddressEditRequest) (*UserReceiveAddressEditResponse, error)
	// 删除收获地址
	DelUserReceiveAddress(context.Context, *UserReceiveAddressDelRequest) (*UserReceiveAddressDelResponse, error)
	// 获取收获地址列表
	GetUserReceiveAddressList(context.Context, *UserReceiveAddressListRequest) (*UserReceiveAddressListResponse, error)
	// 添加收藏
	AddUserCollection(context.Context, *UserCollectionAddRequest) (*UserCollectionAddResponse, error)
	// 删除收藏
	DelUserCollection(context.Context, *UserCollectionDelRequest) (*UserCollectionDelResponse, error)
	// 收藏列表
	GetUserCollectionList(context.Context, *UserCollectionListRequest) (*UserCollectionListResponse, error)
	// 根据主键id,查询收获地址
	GetUserReceiveAddressInfo(context.Context, *UserReceiveAddressInfoRequest) (*UserReceiveAddress, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServer) UserInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (UnimplementedUserServer) AddUserReceiveAddress(context.Context, *UserReceiveAddressAddRequest) (*UserReceiveAddressAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserReceiveAddress not implemented")
}
func (UnimplementedUserServer) EditUserReceiveAddress(context.Context, *UserReceiveAddressEditRequest) (*UserReceiveAddressEditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUserReceiveAddress not implemented")
}
func (UnimplementedUserServer) DelUserReceiveAddress(context.Context, *UserReceiveAddressDelRequest) (*UserReceiveAddressDelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUserReceiveAddress not implemented")
}
func (UnimplementedUserServer) GetUserReceiveAddressList(context.Context, *UserReceiveAddressListRequest) (*UserReceiveAddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserReceiveAddressList not implemented")
}
func (UnimplementedUserServer) AddUserCollection(context.Context, *UserCollectionAddRequest) (*UserCollectionAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserCollection not implemented")
}
func (UnimplementedUserServer) DelUserCollection(context.Context, *UserCollectionDelRequest) (*UserCollectionDelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUserCollection not implemented")
}
func (UnimplementedUserServer) GetUserCollectionList(context.Context, *UserCollectionListRequest) (*UserCollectionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCollectionList not implemented")
}
func (UnimplementedUserServer) GetUserReceiveAddressInfo(context.Context, *UserReceiveAddressInfoRequest) (*UserReceiveAddress, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserReceiveAddressInfo not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call pancis, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddUserReceiveAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReceiveAddressAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddUserReceiveAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddUserReceiveAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddUserReceiveAddress(ctx, req.(*UserReceiveAddressAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_EditUserReceiveAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReceiveAddressEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).EditUserReceiveAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_EditUserReceiveAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).EditUserReceiveAddress(ctx, req.(*UserReceiveAddressEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DelUserReceiveAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReceiveAddressDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DelUserReceiveAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DelUserReceiveAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DelUserReceiveAddress(ctx, req.(*UserReceiveAddressDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserReceiveAddressList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReceiveAddressListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserReceiveAddressList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserReceiveAddressList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserReceiveAddressList(ctx, req.(*UserReceiveAddressListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddUserCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCollectionAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddUserCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddUserCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddUserCollection(ctx, req.(*UserCollectionAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DelUserCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCollectionDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DelUserCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DelUserCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DelUserCollection(ctx, req.(*UserCollectionDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserCollectionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCollectionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserCollectionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserCollectionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserCollectionList(ctx, req.(*UserCollectionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserReceiveAddressInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReceiveAddressInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserReceiveAddressInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserReceiveAddressInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserReceiveAddressInfo(ctx, req.(*UserReceiveAddressInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _User_UserInfo_Handler,
		},
		{
			MethodName: "addUserReceiveAddress",
			Handler:    _User_AddUserReceiveAddress_Handler,
		},
		{
			MethodName: "editUserReceiveAddress",
			Handler:    _User_EditUserReceiveAddress_Handler,
		},
		{
			MethodName: "delUserReceiveAddress",
			Handler:    _User_DelUserReceiveAddress_Handler,
		},
		{
			MethodName: "getUserReceiveAddressList",
			Handler:    _User_GetUserReceiveAddressList_Handler,
		},
		{
			MethodName: "addUserCollection",
			Handler:    _User_AddUserCollection_Handler,
		},
		{
			MethodName: "delUserCollection",
			Handler:    _User_DelUserCollection_Handler,
		},
		{
			MethodName: "getUserCollectionList",
			Handler:    _User_GetUserCollectionList_Handler,
		},
		{
			MethodName: "getUserReceiveAddressInfo",
			Handler:    _User_GetUserReceiveAddressInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
